### GroupBy() --> makes a new table of every group on the basis of a categorical column

In [1]:
import numpy as np
import pandas as pd

In [2]:
movies=pd.read_csv("~/Machine Learning/Pandas/Datasets/imdb-top-1000.csv")
movies

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
0,The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
1,The Godfather,1972,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0
2,The Dark Knight,2008,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
3,The Godfather: Part II,1974,202,Crime,9.0,Francis Ford Coppola,Al Pacino,1129952,57300000.0,90.0
4,12 Angry Men,1957,96,Crime,9.0,Sidney Lumet,Henry Fonda,689845,4360000.0,96.0
...,...,...,...,...,...,...,...,...,...,...
995,Breakfast at Tiffany's,1961,115,Comedy,7.6,Blake Edwards,Audrey Hepburn,166544,679874270.0,76.0
996,Giant,1956,201,Drama,7.6,George Stevens,Elizabeth Taylor,34075,195217415.0,84.0
997,From Here to Eternity,1953,118,Drama,7.6,Fred Zinnemann,Burt Lancaster,43374,30500000.0,85.0
998,Lifeboat,1944,97,Drama,7.6,Alfred Hitchcock,Tallulah Bankhead,26471,852142728.0,78.0
999,The 39 Steps,1935,86,Crime,7.6,Alfred Hitchcock,Robert Donat,51853,302787539.0,93.0

In [3]:
genre=movies.groupby("Genre")
genre

##### Applying builtin aggregation fuctions on groupby objects

In [4]:
genre.std(numeric_only=True)

             Runtime  IMDB_Rating    No_of_Votes         Gross  Metascore
Genre
Action     28.500706     0.304258  432946.814748  2.256724e+08  12.421252
Adventure  33.317320     0.229781  301188.347642  1.697543e+08  12.345393
Animation  14.530471     0.253221  262173.231571  2.091840e+08   8.813646
Biography  25.514466     0.267140  271284.191372  1.363251e+08  11.028187
Comedy     22.946213     0.228771  188653.570564  1.946513e+08  11.829160
Crime      27.689231     0.335477  373999.730656  1.571191e+08  13.099102
Drama      27.740490     0.267229  305554.162841  2.201164e+08  12.744687
Family     10.606602     0.000000  137008.302816  3.048412e+08  16.970563
Fantasy    12.727922     0.141421   22179.111299  7.606861e+07        NaN
Film-Noir   4.000000     0.152753   54649.083277  7.048472e+07   1.527525
Horror     13.604812     0.311302  234883.508691  9.965017e+07  15.362291
Mystery    14.475423     0.310791  404621.915297  1.567524e+08  18.604435
Thriller         NaN          NaN            NaN           NaN        NaN
Western    17.153717     0.420317  263489.554280  1.230626e+07   9.032349

In [5]:
genre.mean(numeric_only=True).head(3)

              Runtime  IMDB_Rating    No_of_Votes         Gross  Metascore
Genre
Action     129.046512     7.949419  420246.581395  1.897224e+08  73.419580
Adventure  134.111111     7.937500  313557.819444  1.319017e+08  78.437500
Animation   99.585366     7.930488  268032.073171  1.784326e+08  81.093333

##### find the top 3 genres by total earning

In [6]:
genre['Gross'].sum().sort_values(ascending=False).head(3)

Genre
Drama     3.540997e+10
Action    3.263226e+10
Comedy    1.566387e+10
Name: Gross, dtype: float64

#####  find the genre with highest avg IMDB rating

In [7]:
genre['IMDB_Rating'].mean().sort_values(ascending=False).head(1)

Genre
Western    8.35
Name: IMDB_Rating, dtype: float64

##### find director with most popularity

In [8]:
movies.groupby('Director')['No_of_Votes'].sum().sort_values(ascending=False).head(1)

Director
Christopher Nolan    11578345
Name: No_of_Votes, dtype: int64

##### find number of movies done by each actor

In [9]:
movies['Star1'].value_counts()

Star1
Tom Hanks            12
Robert De Niro       11
Al Pacino            10
Clint Eastwood       10
Leonardo DiCaprio     9
                     ..
Phil Harris           1
David Hemmings        1
John Lennon           1
Tallulah Bankhead     1
Robert Donat          1
Name: count, Length: 660, dtype: int64

In [10]:
movies.groupby('Star1')['Series_Title'].count().sort_values(ascending=False)

Star1
Tom Hanks             12
Robert De Niro        11
Al Pacino             10
Clint Eastwood        10
Humphrey Bogart        9
                      ..
Günes Sensoy           1
Haluk Bilginer         1
Harriet Andersson      1
Harry Dean Stanton     1
Griffin Dunne          1
Name: Series_Title, Length: 660, dtype: int64

In [11]:
#len() --> tells the number of groups made
len(genre)

14

In [12]:
#size() --> tells the number of rows in each group
genre.size()

Genre
Action       172
Adventure     72
Animation     82
Biography     88
Comedy       155
Crime        107
Drama        289
Family         2
Fantasy        2
Film-Noir      3
Horror        11
Mystery       12
Thriller       1
Western        4
dtype: int64

In [13]:
#first()/last()/nth() --> gives the first,last and nth rows of each group
genre.first()

,Series_Title,Released_Year,Runtime,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,
Action,The Dark Knight,2008,152,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
Adventure,Interstellar,2014,169,8.6,Christopher Nolan,Matthew McConaughey,1512360,188020017.0,74.0
Animation,Sen to Chihiro no kamikakushi,2001,125,8.6,Hayao Miyazaki,Daveigh Chase,651376,10055859.0,96.0
Biography,Schindler's List,1993,195,8.9,Steven Spielberg,Liam Neeson,1213505,96898818.0,94.0
Comedy,Gisaengchung,2019,132,8.6,Bong Joon Ho,Kang-ho Song,552778,53367844.0,96.0
Crime,The Godfather,1972,175,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0
Drama,The Shawshank Redemption,1994,142,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
Family,E.T. the Extra-Terrestrial,1982,115,7.8,Steven Spielberg,Henry Thomas,372490,435110554.0,91.0
Fantasy,Das Cabinet des Dr. Caligari,1920,76,8.1,Robert Wiene,Werner Krauss,57428,337574718.0,NaN
Film-Noir,The Third Man,1949,104,8.1,Carol Reed,Orson Welles,158731,449191.0,97.0
Horror,Psycho,1960,109,8.5,Alfred Hitchcock,Anthony Perkins,604211,32000000.0,97.0
Mystery,Memento,2000,113,8.4,Christopher Nolan,Guy Pearce,1125712,25544867.0,80.0
Thriller,Wait Until Dark,1967,108,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
Western,"Il buono, il brutto, il cattivo",1966,161,8.8,Sergio Leone,Clint Eastwood,688390,6100000.0,90.0

In [14]:
genre.nth(10)

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
39,Gladiator,2000,155,Action,8.5,Ridley Scott,Russell Crowe,1341460,187705427.0,67.0
41,The Usual Suspects,1995,106,Crime,8.5,Bryan Singer,Kevin Spacey,991208,23341568.0,77.0
45,Nuovo Cinema Paradiso,1988,155,Drama,8.5,Giuseppe Tornatore,Philippe Noiret,230763,11990401.0,80.0
117,The Apartment,1960,125,Comedy,8.3,Billy Wilder,Jack Lemmon,164363,18600000.0,94.0
146,Up,2009,96,Animation,8.2,Pete Docter,Bob Peterson,935507,293004164.0,88.0
147,The Wolf of Wall Street,2013,180,Biography,8.2,Martin Scorsese,Leonardo DiCaprio,1187498,116900694.0,75.0
191,The Treasure of the Sierra Madre,1948,126,Adventure,8.2,John Huston,Humphrey Bogart,114304,5014000.0,98.0
948,The Others,2001,101,Horror,7.6,Alejandro Amenábar,Nicole Kidman,337651,96522687.0,74.0
959,Dark City,1998,100,Mystery,7.6,Alex Proyas,Rufus Sewell,187927,14378331.0,66.0

In [15]:
#get_group() --> gives a certain group from a groupby object

genre.get_group('Action')

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
2,The Dark Knight,2008,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
5,The Lord of the Rings: The Return of the King,2003,201,Action,8.9,Peter Jackson,Elijah Wood,1642758,377845905.0,94.0
8,Inception,2010,148,Action,8.8,Christopher Nolan,Leonardo DiCaprio,2067042,292576195.0,74.0
10,The Lord of the Rings: The Fellowship of the Ring,2001,178,Action,8.8,Peter Jackson,Elijah Wood,1661481,315544750.0,92.0
13,The Lord of the Rings: The Two Towers,2002,179,Action,8.7,Peter Jackson,Elijah Wood,1485555,342551365.0,87.0
...,...,...,...,...,...,...,...,...,...,...
968,Falling Down,1993,113,Action,7.6,Joel Schumacher,Michael Douglas,171640,40903593.0,56.0
979,Lethal Weapon,1987,109,Action,7.6,Richard Donner,Mel Gibson,236894,65207127.0,68.0
982,Mad Max 2,1981,96,Action,7.6,George Miller,Mel Gibson,166588,12465371.0,77.0
983,The Warriors,1979,92,Action,7.6,Walter Hill,Michael Beck,93878,22490039.0,65.0
985,Escape from Alcatraz,1979,112,Action,7.6,Don Siegel,Clint Eastwood,121731,43000000.0,76.0

In [16]:
#groups --> return a key value pair of every group where key=name of group and value is a list of indices of that group
genre.groups

{'Action': [2, 5, 8, 10, 13, 14, 16, 29, 30, 31, 39, 42, 44, 55, 57, 59, 60, 63, 68, 72, 106, 109, 129, 130, 134, 140, 142, 144, 152, 155, 160, 161, 166, 168, 171, 172, 177, 181, 194, 201, 202, 216, 217, 223, 224, 236, 241, 262, 275, 294, 308, 320, 325, 326, 331, 337, 339, 340, 343, 345, 348, 351, 353, 356, 357, 362, 368, 369, 375, 376, 390, 410, 431, 436, 473, 477, 479, 482, 488, 493, 496, 502, 507, 511, 532, 535, 540, 543, 564, 569, 570, 573, 577, 582, 583, 602, 605, 608, 615, 623, ...], 'Adventure': [21, 47, 93, 110, 114, 116, 118, 137, 178, 179, 191, 193, 209, 226, 231, 247, 267, 273, 281, 300, 301, 304, 306, 323, 329, 361, 366, 377, 402, 406, 415, 426, 458, 470, 497, 498, 506, 513, 514, 537, 549, 552, 553, 566, 576, 604, 609, 618, 638, 647, 675, 681, 686, 692, 711, 713, 739, 755, 781, 797, 798, 851, 873, 884, 912, 919, 947, 957, 964, 966, 984, 991], 'Animation': [23, 43, 46, 56, 58, 61, 66, 70, 101, 135, 146, 151, 158, 170, 197, 205, 211, 213, 219, 229, 230, 242, 245, 246, 270, 330, 332, 358, 367, 378, 386, 389, 394, 395, 399, 401, 405, 409, 469, 499, 510, 516, 518, 522, 578, 586, 592, 595, 596, 599, 633, 640, 643, 651, 665, 672, 694, 728, 740, 741, 744, 756, 758, 761, 771, 783, 796, 799, 822, 828, 843, 875, 891, 892, 902, 906, 920, 956, 971, 976, 986, 992], 'Biography': [7, 15, 18, 35, 38, 54, 102, 107, 131, 139, 147, 157, 159, 173, 176, 212, 215, 218, 228, 235, 243, 263, 276, 282, 290, 298, 317, 328, 338, 342, 346, 359, 360, 365, 372, 373, 385, 411, 416, 418, 424, 429, 484, 525, 536, 542, 545, 575, 579, 587, 600, 606, 614, 622, 632, 635, 644, 649, 650, 657, 671, 673, 684, 729, 748, 753, 757, 759, 766, 770, 779, 809, 810, 815, 820, 831, 849, 858, 877, 882, 897, 910, 915, 923, 940, 949, 952, 987], 'Comedy': [19, 26, 51, 52, 64, 78, 83, 95, 96, 112, 117, 120, 127, 128, 132, 153, 169, 183, 192, 204, 207, 208, 214, 221, 233, 238, 240, 250, 251, 252, 256, 261, 266, 277, 284, 311, 313, 316, 318, 322, 327, 374, 379, 381, 392, 396, 403, 413, 414, 417, 427, 435, 445, 446, 449, 455, 459, 460, 463, 464, 466, 471, 472, 475, 481, 490, 494, 500, 503, 509, 526, 528, 530, 531, 533, 538, 539, 541, 547, 557, 558, 562, 563, 565, 574, 591, 593, 594, 598, 613, 626, 630, 660, 662, 667, 679, 680, 683, 687, 701, ...], 'Crime': [1, 3, 4, 6, 22, 25, 27, 28, 33, 37, 41, 71, 77, 79, 86, 87, 103, 108, 111, 113, 123, 125, 133, 136, 162, 163, 164, 165, 180, 186, 187, 189, 198, 222, 232, 239, 255, 257, 287, 288, 299, 305, 335, 363, 364, 380, 384, 397, 437, 438, 441, 442, 444, 450, 451, 465, 474, 480, 485, 487, 505, 512, 519, 520, 523, 527, 546, 556, 560, 584, 597, 603, 607, 611, 621, 639, 653, 664, 669, 676, 695, 708, 723, 762, 763, 767, 775, 791, 795, 802, 811, 823, 827, 833, 885, 895, 921, 922, 926, 938, ...], 'Drama': [0, 9, 11, 17, 20, 24, 32, 34, 36, 40, 45, 50, 53, 62, 65, 67, 73, 74, 76, 80, 82, 84, 85, 88, 89, 90, 91, 92, 94, 97, 98, 99, 100, 104, 105, 121, 122, 124, 126, 138, 141, 143, 148, 149, 150, 154, 156, 167, 174, 175, 182, 184, 185, 188, 190, 195, 196, 199, 200, 203, 206, 210, 225, 227, 234, 237, 244, 248, 249, 253, 254, 258, 259, 260, 264, 265, 268, 269, 272, 274, 278, 279, 280, 283, 285, 286, 289, 291, 292, 293, 295, 296, 297, 302, 303, 307, 310, 312, 314, 315, ...], 'Family': [688, 698], 'Fantasy': [321, 568], 'Film-Noir': [309, 456, 712], 'Horror': [49, 75, 271, 419, 544, 707, 724, 844, 876, 932, 948], 'Mystery': [69, 81, 119, 145, 220, 393, 420, 714, 829, 899, 959, 961], 'Thriller': [700], 'Western': [12, 48, 115, 691]}

In [17]:
#describe() --> just like DataFrame
genre.describe()

          Runtime                                                              \
            count        mean        std    min     25%    50%     75%    max
Genre
Action      172.0  129.046512  28.500706   45.0  110.75  127.5  143.25  321.0
Adventure    72.0  134.111111  33.317320   88.0  109.00  127.0  149.00  228.0
Animation    82.0   99.585366  14.530471   71.0   90.00   99.5  106.75  137.0
Biography    88.0  136.022727  25.514466   93.0  120.00  129.0  146.25  209.0
Comedy      155.0  112.129032  22.946213   68.0   96.00  106.0  124.50  188.0
Crime       107.0  126.392523  27.689231   80.0  106.50  122.0  141.50  229.0
Drama       289.0  124.737024  27.740490   64.0  105.00  121.0  137.00  242.0
Family        2.0  107.500000  10.606602  100.0  103.75  107.5  111.25  115.0
Fantasy       2.0   85.000000  12.727922   76.0   80.50   85.0   89.50   94.0
Film-Noir     3.0  104.000000   4.000000  100.0  102.00  104.0  106.00  108.0
Horror       11.0  102.090909  13.604812   71.0   98.00  103.0  109.00  122.0
Mystery      12.0  119.083333  14.475423   96.0  110.75  117.5  130.25  138.0
Thriller      1.0  108.000000        NaN  108.0  108.00  108.0  108.00  108.0
Western       4.0  148.250000  17.153717  132.0  134.25  148.0  162.00  165.0

          IMDB_Rating            ...         Gross              Metascore  \
                count      mean  ...           75%          max     count
Genre                            ...
Action          172.0  7.949419  ...  2.674437e+08  936662225.0     143.0
Adventure        72.0  7.937500  ...  1.998070e+08  874211619.0      64.0
Animation        82.0  7.930488  ...  2.520612e+08  873839108.0      75.0
Biography        88.0  7.938636  ...  9.829924e+07  753585104.0      79.0
Comedy          155.0  7.901290  ...  8.107809e+07  886752933.0     125.0
Crime           107.0  8.016822  ...  7.102163e+07  790482117.0      87.0
Drama           289.0  7.957439  ...  1.164461e+08  924558264.0     241.0
Family            2.0  7.800000  ...  3.273329e+08  435110554.0       2.0
Fantasy           2.0  8.000000  ...  4.182577e+08  445151978.0       0.0
Film-Noir         3.0  7.966667  ...  6.273068e+07  123353292.0       3.0
Horror           11.0  7.909091  ...  1.362817e+08  298791505.0      11.0
Mystery          12.0  7.975000  ...  1.310949e+08  474203697.0       8.0
Thriller          1.0  7.800000  ...  1.755074e+07   17550741.0       1.0
Western           4.0  8.350000  ...  1.920000e+07   31800000.0       4.0


                mean        std   min    25%   50%    75%    max
Genre
Action     73.419580  12.421252  33.0  65.00  74.0  82.00   98.0
Adventure  78.437500  12.345393  41.0  69.75  80.5  87.25  100.0
Animation  81.093333   8.813646  61.0  75.00  82.0  87.50   96.0
Biography  76.240506  11.028187  48.0  70.50  76.0  84.50   97.0
Comedy     78.720000  11.829160  45.0  72.00  79.0  88.00   99.0
Crime      77.080460  13.099102  47.0  69.50  77.0  87.00  100.0
Drama      79.701245  12.744687  28.0  72.00  82.0  89.00  100.0
Family     79.000000  16.970563  67.0  73.00  79.0  85.00   91.0
Fantasy          NaN        NaN   NaN    NaN   NaN    NaN    NaN
Film-Noir  95.666667   1.527525  94.0  95.00  96.0  96.50   97.0
Horror     80.000000  15.362291  46.0  77.50  87.0  88.50   97.0
Mystery    79.125000  18.604435  52.0  65.25  77.0  98.50  100.0
Thriller   81.000000        NaN  81.0  81.00  81.0  81.00   81.0
Western    78.250000   9.032349  69.0  72.75  77.0  82.50   90.0

[14 rows x 40 columns]

In [18]:
genre.sample(1)

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
63,The Dark Knight Rises,2012,164,Action,8.4,Christopher Nolan,Christian Bale,1516346,448139099.0,78.0
93,Inglourious Basterds,2009,153,Adventure,8.3,Quentin Tarantino,Brad Pitt,1267869,120540719.0,69.0
43,The Lion King,1994,88,Animation,8.5,Roger Allers,Rob Minkoff,942045,422783777.0,88.0
757,Frost/Nixon,2008,122,Biography,7.7,Ron Howard,Frank Langella,103330,18593156.0,80.0
392,Secrets & Lies,1996,136,Comedy,8.0,Mike Leigh,Timothy Spall,37564,13417292.0,91.0
960,Sleepers,1996,147,Crime,7.6,Barry Levinson,Robert De Niro,186734,49100000.0,49.0
258,Dilwale Dulhania Le Jayenge,1995,189,Drama,8.1,Aditya Chopra,Shah Rukh Khan,63516,15121644.0,NaN
688,E.T. the Extra-Terrestrial,1982,115,Family,7.8,Steven Spielberg,Henry Thomas,372490,435110554.0,91.0
568,Nosferatu,1922,94,Fantasy,7.9,F.W. Murnau,Max Schreck,88794,445151978.0,NaN
712,Shadow of a Doubt,1943,108,Film-Noir,7.8,Alfred Hitchcock,Teresa Wright,59556,123353292.0,94.0
948,The Others,2001,101,Horror,7.6,Alejandro Amenábar,Nicole Kidman,337651,96522687.0,74.0
81,Rear Window,1954,112,Mystery,8.4,Alfred Hitchcock,James Stewart,444074,36764313.0,100.0
700,Wait Until Dark,1967,108,Thriller,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
48,Once Upon a Time in the West,1968,165,Western,8.5,Sergio Leone,Henry Fonda,302844,5321508.0,80.0

In [19]:
#nunique() --> returns the number of unique values in each column
genre.nunique()

,Series_Title,Released_Year,Runtime,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,
Action,172,61,78,15,123,121,172,172,50
Adventure,72,49,58,10,59,59,72,72,33
Animation,82,35,41,11,51,77,82,82,29
Biography,88,44,56,13,76,72,88,88,40
Comedy,155,72,70,11,113,133,155,155,44
Crime,106,56,65,14,86,85,107,107,39
Drama,289,83,95,14,211,250,288,287,52
Family,2,2,2,1,2,2,2,2,2
Fantasy,2,2,2,2,2,2,2,2,0
Film-Noir,3,3,3,3,3,3,3,3,3
Horror,11,11,10,8,10,11,11,11,9
Mystery,12,11,10,8,10,11,12,12,7
Thriller,1,1,1,1,1,1,1,1,1
Western,4,4,4,4,2,2,4,4,4

##### agg() --> applies different aggregate functions on a groupby object at once

In [20]:
genre.agg({"Runtime":'mean',
          "Gross":"sum"})

              Runtime         Gross
Genre
Action     129.046512  3.263226e+10
Adventure  134.111111  9.496922e+09
Animation   99.585366  1.463147e+10
Biography  136.022727  8.276358e+09
Comedy     112.129032  1.566387e+10
Crime      126.392523  8.452632e+09
Drama      124.737024  3.540997e+10
Family     107.500000  4.391106e+08
Fantasy     85.000000  7.827267e+08
Film-Noir  104.000000  1.259105e+08
Horror     102.090909  1.034649e+09
Mystery    119.083333  1.256417e+09
Thriller   108.000000  1.755074e+07
Western    148.250000  5.822151e+07

In [21]:
#we can pass a list to apply many aggregate functions to the same columns
genre.agg({"Runtime":['mean','max'],"Gross":['sum','mean']})

              Runtime              Gross
                 mean  max           sum          mean
Genre
Action     129.046512  321  3.263226e+10  1.897224e+08
Adventure  134.111111  228  9.496922e+09  1.319017e+08
Animation   99.585366  137  1.463147e+10  1.784326e+08
Biography  136.022727  209  8.276358e+09  9.404952e+07
Comedy     112.129032  188  1.566387e+10  1.010572e+08
Crime      126.392523  229  8.452632e+09  7.899656e+07
Drama      124.737024  242  3.540997e+10  1.225259e+08
Family     107.500000  115  4.391106e+08  2.195553e+08
Fantasy     85.000000   94  7.827267e+08  3.913633e+08
Film-Noir  104.000000  108  1.259105e+08  4.197018e+07
Horror     102.090909  122  1.034649e+09  9.405902e+07
Mystery    119.083333  138  1.256417e+09  1.047014e+08
Thriller   108.000000  108  1.755074e+07  1.755074e+07
Western    148.250000  165  5.822151e+07  1.455538e+07

##### looping

In [22]:
for group,data in genre:
    print(type(group),type(data))

<class 'str'> <class 'pandas.DataFrame'>
<class 'str'> <class 'pandas.DataFrame'>
<class 'str'> <class 'pandas.DataFrame'>
<class 'str'> <class 'pandas.DataFrame'>
<class 'str'> <class 'pandas.DataFrame'>
<class 'str'> <class 'pandas.DataFrame'>
<class 'str'> <class 'pandas.DataFrame'>
<class 'str'> <class 'pandas.DataFrame'>
<class 'str'> <class 'pandas.DataFrame'>
<class 'str'> <class 'pandas.DataFrame'>
<class 'str'> <class 'pandas.DataFrame'>
<class 'str'> <class 'pandas.DataFrame'>
<class 'str'> <class 'pandas.DataFrame'>
<class 'str'> <class 'pandas.DataFrame'>

In [23]:
for group,data in genre:
    print(group)

Action
Adventure
Animation
Biography
Comedy
Crime
Drama
Family
Fantasy
Film-Noir
Horror
Mystery
Thriller
Western

In [24]:
for group,data in genre:
    print(data)

                                          Series_Title Released_Year  Runtime  \
2                                      The Dark Knight          2008      152
5        The Lord of the Rings: The Return of the King          2003      201
8                                            Inception          2010      148
10   The Lord of the Rings: The Fellowship of the Ring          2001      178
13               The Lord of the Rings: The Two Towers          2002      179
..                                                 ...           ...      ...
968                                       Falling Down          1993      113
979                                      Lethal Weapon          1987      109
982                                          Mad Max 2          1981       96
983                                       The Warriors          1979       92
985                               Escape from Alcatraz          1979      112

      Genre  IMDB_Rating           Director              Star1  No_of_Votes  \
2    Action          9.0  Christopher Nolan     Christian Bale      2303232
5    Action          8.9      Peter Jackson        Elijah Wood      1642758
8    Action          8.8  Christopher Nolan  Leonardo DiCaprio      2067042
10   Action          8.8      Peter Jackson        Elijah Wood      1661481
13   Action          8.7      Peter Jackson        Elijah Wood      1485555
..      ...          ...                ...                ...          ...
968  Action          7.6    Joel Schumacher    Michael Douglas       171640
979  Action          7.6     Richard Donner         Mel Gibson       236894
982  Action          7.6      George Miller         Mel Gibson       166588
983  Action          7.6        Walter Hill       Michael Beck        93878
985  Action          7.6         Don Siegel     Clint Eastwood       121731

           Gross  Metascore
2    534858444.0       84.0
5    377845905.0       94.0
8    292576195.0       74.0
10   315544750.0       92.0
13   342551365.0       87.0
..           ...        ...
968   40903593.0       56.0
979   65207127.0       68.0
982   12465371.0       77.0
983   22490039.0       65.0
985   43000000.0       76.0

[172 rows x 10 columns]
                       Series_Title Released_Year  Runtime      Genre  \
21                     Interstellar          2014      169  Adventure
47               Back to the Future          1985      116  Adventure
93             Inglourious Basterds          2009      153  Adventure
110                        Das Boot          1981      149  Adventure
114           2001: A Space Odyssey          1968      149  Adventure
..                              ...           ...      ...        ...
957  Fear and Loathing in Las Vegas          1998      118  Adventure
964                        Dead Man          1995      121  Adventure
966                       Apollo 13            PG      140  Adventure
984                The Muppet Movie          1979       95  Adventure
991                  Kelly's Heroes          1970      144  Adventure

     IMDB_Rating           Director                Star1  No_of_Votes  \
21           8.6  Christopher Nolan  Matthew McConaughey      1512360
47           8.5    Robert Zemeckis       Michael J. Fox      1058081
93           8.3  Quentin Tarantino            Brad Pitt      1267869
110          8.3  Wolfgang Petersen      Jürgen Prochnow       231855
114          8.3    Stanley Kubrick          Keir Dullea       603517
..           ...                ...                  ...          ...
957          7.6      Terry Gilliam          Johnny Depp       259753
964          7.6       Jim Jarmusch          Johnny Depp        90442
966          7.6         Ron Howard            Tom Hanks       269197
984          7.6      James Frawley           Jim Henson        32802
991          7.6    Brian G. Hutton       Clint Eastwood        45338

           Gross  Metascore
21   188020017.0       74.0
47   210609762.0       87.0
93   120540719.0       69.0
110   11487676.0       86.0
114   56954992.0       84.0
..           ...        ...
957   10680275.0       41.0
964    1037847.0       62.0
966  173837933.0       77.0
984   76657000.0       74.0
991    1378435.0       50.0

[72 rows x 10 columns]
                          Series_Title Released_Year  Runtime      Genre  \
23       Sen to Chihiro no kamikakushi          2001      125  Animation
43                       The Lion King          1994       88  Animation
46                      Hotaru no haka          1988       89  Animation
56                      Kimi no na wa.          2016      106  Animation
58   Spider-Man: Into the Spider-Verse          2018      117  Animation
..                                 ...           ...      ...        ...
956                              Mulan          1998       88  Animation
971                  Omohide poro poro          1991      118  Animation
976                 The Little Mermaid          1989       83  Animation
986                     Watership Down          1978       91  Animation
992                    The Jungle Book          1967       78  Animation

     IMDB_Rating             Director             Star1  No_of_Votes  \
23           8.6       Hayao Miyazaki     Daveigh Chase       651376
43           8.5         Roger Allers       Rob Minkoff       942045
46           8.5        Isao Takahata   Tsutomu Tatsumi       235231
56           8.4       Makoto Shinkai  Ryûnosuke Kamiki       194838
58           8.4      Bob Persichetti      Peter Ramsey       375110
..           ...                  ...               ...          ...
956          7.6        Tony Bancroft        Barry Cook       256906
971          7.6        Isao Takahata         Miki Imai        27071
976          7.6         Ron Clements       John Musker       237696
986          7.6         Martin Rosen       John Hubley        33656
992          7.6  Wolfgang Reitherman       Phil Harris       166409

           Gross  Metascore
23    10055859.0       96.0
43   422783777.0       88.0
46   150734678.0       94.0
56     5017246.0       79.0
58   190241310.0       87.0
..           ...        ...
956  120620254.0       71.0
971     453243.0       90.0
976  111543479.0       88.0
986  232841485.0       64.0
992  141843612.0       65.0

[82 rows x 10 columns]
          Series_Title Released_Year  Runtime      Genre  IMDB_Rating  \
7     Schindler's List          1993      195  Biography          8.9
15          Goodfellas          1990      146  Biography          8.7
18            Hamilton          2020      160  Biography          8.6
35    The Intouchables          2011      112  Biography          8.5
38         The Pianist          2002      150  Biography          8.5
..                 ...           ...      ...        ...          ...
923     La Vie En Rose          2007      140  Biography          7.6
940  Finding Neverland          2004      106  Biography          7.6
949               Blow          2001      124  Biography          7.6
952      The Hurricane          1999      146  Biography          7.6
987   Midnight Express          1978      121  Biography          7.6

             Director               Star1  No_of_Votes        Gross  Metascore
7    Steven Spielberg         Liam Neeson      1213505   96898818.0       94.0
15    Martin Scorsese      Robert De Niro      1020727   46836394.0       90.0
18        Thomas Kail  Lin-Manuel Miranda        55291  440984783.0       90.0
35    Olivier Nakache       Éric Toledano       760360   13182281.0       57.0
38     Roman Polanski        Adrien Brody       729603   32572577.0       85.0
..                ...                 ...          ...          ...        ...
923     Olivier Dahan    Marion Cotillard        82781   10301706.0       66.0
940      Marc Forster         Johnny Depp       198677   51680613.0       67.0
949         Ted Demme         Johnny Depp       240714   52990775.0       52.0
952    Norman Jewison   Denzel Washington        91557   50668906.0       74.0
987       Alan Parker          Brad Davis        73662   35000000.0       59.0

[88 rows x 10 columns]
                                       Series_Title Released_Year  Runtime  \
19                                     Gisaengchung          2019      132
26                                  La vita è bella          1997      116
51                                     Modern Times          1936       87
52                                      City Lights          1931       87
64                                         3 Idiots          2009      170
..                                              ...           ...      ...
977  The Naked Gun: From the Files of Police Squad!          1988       85
978                    Planes, Trains & Automobiles          1987       93
989                                The Long Goodbye          1973      112
994                              A Hard Day's Night          1964       87
995                          Breakfast at Tiffany's          1961      115

      Genre  IMDB_Rating         Director            Star1  No_of_Votes  \
19   Comedy          8.6     Bong Joon Ho     Kang-ho Song       552778
26   Comedy          8.6  Roberto Benigni  Roberto Benigni       623629
51   Comedy          8.5  Charles Chaplin  Charles Chaplin       217881
52   Comedy          8.5  Charles Chaplin  Charles Chaplin       167839
64   Comedy          8.4  Rajkumar Hirani       Aamir Khan       344445
..      ...          ...              ...              ...          ...
977  Comedy          7.6     David Zucker   Leslie Nielsen       152871
978  Comedy          7.6      John Hughes     Steve Martin       124773
989  Comedy          7.6    Robert Altman    Elliott Gould        26337
994  Comedy          7.6   Richard Lester      John Lennon        40351
995  Comedy          7.6    Blake Edwards   Audrey Hepburn       166544

           Gross  Metascore
19    53367844.0       96.0
26    57598247.0       59.0
51      163245.0       96.0
52       19181.0       99.0
64     6532908.0       67.0
..           ...        ...
977   78756177.0       76.0
978   49530280.0       72.0
989     959000.0       87.0
994   13780024.0       96.0
995  679874270.0       76.0

[155 rows x 10 columns]
                Series_Title Released_Year  Runtime  Genre  IMDB_Rating  \
1              The Godfather          1972      175  Crime          9.2
3     The Godfather: Part II          1974      202  Crime          9.0
4               12 Angry Men          1957       96  Crime          9.0
6               Pulp Fiction          1994      154  Crime          8.9
22            Cidade de Deus          2002      130  Crime          8.6
..                       ...           ...      ...    ...          ...
958              Funny Games          1997      108  Crime          7.6
960                 Sleepers          1996      147  Crime          7.6
974  The Godfather: Part III          1990      162  Crime          7.6
980             Blood Simple          1984       99  Crime          7.6
999             The 39 Steps          1935       86  Crime          7.6

                 Director           Star1  No_of_Votes        Gross  Metascore
1    Francis Ford Coppola   Marlon Brando      1620367  134966411.0      100.0
3    Francis Ford Coppola       Al Pacino      1129952   57300000.0       90.0
4            Sidney Lumet     Henry Fonda       689845    4360000.0       96.0
6       Quentin Tarantino   John Travolta      1826188  107928762.0       94.0
22     Fernando Meirelles      Kátia Lund       699256    7563397.0       79.0
..                    ...             ...          ...          ...        ...
958        Michael Haneke  Susanne Lothar        65058  217345863.0       69.0
960        Barry Levinson  Robert De Niro       186734   49100000.0       49.0
974  Francis Ford Coppola       Al Pacino       359809   66666062.0       60.0
980             Joel Coen      Ethan Coen        87745    2150000.0       82.0
999      Alfred Hitchcock    Robert Donat        51853  302787539.0       93.0

[107 rows x 10 columns]
                        Series_Title Released_Year  Runtime  Genre  \
0           The Shawshank Redemption          1994      142  Drama
9                         Fight Club          1999      139  Drama
11                      Forrest Gump          1994      142  Drama
17   One Flew Over the Cuckoo's Nest          1975      133  Drama
20                   Soorarai Pottru          2020      153  Drama
..                               ...           ...      ...    ...
990                     Giù la testa          1971      157  Drama
993                           Blowup          1966      111  Drama
996                            Giant          1956      201  Drama
997            From Here to Eternity          1953      118  Drama
998                         Lifeboat          1944       97  Drama

     IMDB_Rating                Director              Star1  No_of_Votes  \
0            9.3          Frank Darabont        Tim Robbins      2343110
9            8.8           David Fincher          Brad Pitt      1854740
11           8.8         Robert Zemeckis          Tom Hanks      1809221
17           8.7            Milos Forman     Jack Nicholson       918088
20           8.6           Sudha Kongara             Suriya        54995
..           ...                     ...                ...          ...
990          7.6            Sergio Leone        Rod Steiger        30144
993          7.6  Michelangelo Antonioni     David Hemmings        56513
996          7.6          George Stevens   Elizabeth Taylor        34075
997          7.6          Fred Zinnemann     Burt Lancaster        43374
998          7.6        Alfred Hitchcock  Tallulah Bankhead        26471

           Gross  Metascore
0     28341469.0       80.0
9     37030102.0       66.0
11   330252182.0       82.0
17   112000000.0       83.0
20   556832648.0        NaN
..           ...        ...
990     696690.0       77.0
993  632532802.0       82.0
996  195217415.0       84.0
997   30500000.0       85.0
998  852142728.0       78.0

[289 rows x 10 columns]
                            Series_Title Released_Year  Runtime   Genre  \
688           E.T. the Extra-Terrestrial          1982      115  Family
698  Willy Wonka & the Chocolate Factory          1971      100  Family

     IMDB_Rating          Director         Star1  No_of_Votes        Gross  \
688          7.8  Steven Spielberg  Henry Thomas       372490  435110554.0
698          7.8        Mel Stuart   Gene Wilder       178731    4000000.0

     Metascore
688       91.0
698       67.0
                     Series_Title Released_Year  Runtime    Genre  \
321  Das Cabinet des Dr. Caligari          1920       76  Fantasy
568                     Nosferatu          1922       94  Fantasy

     IMDB_Rating      Director          Star1  No_of_Votes        Gross  \
321          8.1  Robert Wiene  Werner Krauss        57428  337574718.0
568          7.9   F.W. Murnau    Max Schreck        88794  445151978.0

     Metascore
321        NaN
568        NaN
           Series_Title Released_Year  Runtime      Genre  IMDB_Rating  \
309       The Third Man          1949      104  Film-Noir          8.1
456  The Maltese Falcon          1941      100  Film-Noir          8.0
712   Shadow of a Doubt          1943      108  Film-Noir          7.8

             Director            Star1  No_of_Votes        Gross  Metascore
309        Carol Reed     Orson Welles       158731     449191.0       97.0
456       John Huston  Humphrey Bogart       148928    2108060.0       96.0
712  Alfred Hitchcock    Teresa Wright        59556  123353292.0       94.0
                 Series_Title Released_Year  Runtime   Genre  IMDB_Rating  \
49                     Psycho          1960      109  Horror          8.5
75                      Alien          1979      117  Horror          8.4
271                 The Thing          1982      109  Horror          8.1
419              The Exorcist          1973      122  Horror          8.0
544  Night of the Living Dead          1968       96  Horror          7.9
707             The Innocents          1961      100  Horror          7.8
724                   Get Out          2017      104  Horror          7.7
844                 Halloween          1978       91  Horror          7.7
876         The Invisible Man          1933       71  Horror          7.7
932                       Saw          2004      103  Horror          7.6
948                The Others          2001      101  Horror          7.6

               Director             Star1  No_of_Votes        Gross  Metascore
49     Alfred Hitchcock   Anthony Perkins       604211   32000000.0       97.0
75         Ridley Scott  Sigourney Weaver       787806   78900000.0       89.0
271      John Carpenter      Kurt Russell       371271   13782838.0       57.0
419    William Friedkin     Ellen Burstyn       362393  232906145.0       81.0
544    George A. Romero       Duane Jones       116557      89029.0       89.0
707        Jack Clayton      Deborah Kerr        27007    2616000.0       88.0
724        Jordan Peele    Daniel Kaluuya       492851  176040665.0       85.0
844      John Carpenter  Donald Pleasence       233106   47000000.0       87.0
876         James Whale      Claude Rains        30683  298791505.0       87.0
932           James Wan        Cary Elwes       379020   56000369.0       46.0
948  Alejandro Amenábar     Nicole Kidman       337651   96522687.0       74.0
          Series_Title Released_Year  Runtime    Genre  IMDB_Rating  \
69             Memento          2000      113  Mystery          8.4
81         Rear Window          1954      112  Mystery          8.4
119            Vertigo          1958      128  Mystery          8.3
145     Shutter Island          2010      138  Mystery          8.2
220            Kahaani          2012      122  Mystery          8.1
393     Twelve Monkeys          1995      129  Mystery          8.0
420             Sleuth          1972      138  Mystery          8.0
714  The Lady Vanishes          1938       96  Mystery          7.8
829          Spoorloos          1988      107  Mystery          7.7
899          El cuerpo          2012      112  Mystery          7.6
959          Dark City          1998      100  Mystery          7.6
961       Lost Highway          1997      134  Mystery          7.6

                 Director                     Star1  No_of_Votes        Gross  \
69      Christopher Nolan                Guy Pearce      1125712   25544867.0
81       Alfred Hitchcock             James Stewart       444074   36764313.0
119      Alfred Hitchcock             James Stewart       364368    3200000.0
145       Martin Scorsese         Leonardo DiCaprio      1129894  128012934.0
220           Sujoy Ghosh               Vidya Balan        57806    1035953.0
393         Terry Gilliam              Bruce Willis       578443   57141459.0
420  Joseph L. Mankiewicz          Laurence Olivier        44748    4081254.0
714      Alfred Hitchcock         Margaret Lockwood        47400  474203697.0
829        George Sluizer  Bernard-Pierre Donnadieu        33982  367916835.0
899           Oriol Paulo             Jose Coronado        57549  140340673.0
959           Alex Proyas              Rufus Sewell       187927   14378331.0
961           David Lynch              Bill Pullman       131101    3796699.0

     Metascore
69        80.0
81       100.0
119      100.0
145       63.0
220        NaN
393       74.0
420        NaN
714       98.0
829        NaN
899        NaN
959       66.0
961       52.0
        Series_Title Released_Year  Runtime     Genre  IMDB_Rating  \
700  Wait Until Dark          1967      108  Thriller          7.8

          Director           Star1  No_of_Votes       Gross  Metascore
700  Terence Young  Audrey Hepburn        27733  17550741.0       81.0

In [25]:
#find 3rd movie of each group
for _ in genre:
    print(genre.nth(3))

                                          Series_Title Released_Year  Runtime  \
6                                         Pulp Fiction          1994      154
10   The Lord of the Rings: The Fellowship of the Ring          2001      178
17                     One Flew Over the Cuckoo's Nest          1975      133
35                                    The Intouchables          2011      112
52                                         City Lights          1931       87
56                                      Kimi no na wa.          2016      106
110                                           Das Boot          1981      149
145                                     Shutter Island          2010      138
419                                       The Exorcist          1973      122
691                             The Outlaw Josey Wales          1976      135

         Genre  IMDB_Rating           Director              Star1  \
6        Crime          8.9  Quentin Tarantino      John Travolta
10      Action          8.8      Peter Jackson        Elijah Wood
17       Drama          8.7       Milos Forman     Jack Nicholson
35   Biography          8.5    Olivier Nakache      Éric Toledano
52      Comedy          8.5    Charles Chaplin    Charles Chaplin
56   Animation          8.4     Makoto Shinkai   Ryûnosuke Kamiki
110  Adventure          8.3  Wolfgang Petersen    Jürgen Prochnow
145    Mystery          8.2    Martin Scorsese  Leonardo DiCaprio
419     Horror          8.0   William Friedkin      Ellen Burstyn
691    Western          7.8     Clint Eastwood     Clint Eastwood

     No_of_Votes        Gross  Metascore
6        1826188  107928762.0       94.0
10       1661481  315544750.0       92.0
17        918088  112000000.0       83.0
35        760360   13182281.0       57.0
52        167839      19181.0       99.0
56        194838    5017246.0       79.0
110       231855   11487676.0       86.0
145      1129894  128012934.0       63.0
419       362393  232906145.0       81.0
691        65659   31800000.0       69.0
                                          Series_Title Released_Year  Runtime  \
6                                         Pulp Fiction          1994      154
10   The Lord of the Rings: The Fellowship of the Ring          2001      178
17                     One Flew Over the Cuckoo's Nest          1975      133
35                                    The Intouchables          2011      112
52                                         City Lights          1931       87
56                                      Kimi no na wa.          2016      106
110                                           Das Boot          1981      149
145                                     Shutter Island          2010      138
419                                       The Exorcist          1973      122
691                             The Outlaw Josey Wales          1976      135

         Genre  IMDB_Rating           Director              Star1  \
6        Crime          8.9  Quentin Tarantino      John Travolta
10      Action          8.8      Peter Jackson        Elijah Wood
17       Drama          8.7       Milos Forman     Jack Nicholson
35   Biography          8.5    Olivier Nakache      Éric Toledano
52      Comedy          8.5    Charles Chaplin    Charles Chaplin
56   Animation          8.4     Makoto Shinkai   Ryûnosuke Kamiki
110  Adventure          8.3  Wolfgang Petersen    Jürgen Prochnow
145    Mystery          8.2    Martin Scorsese  Leonardo DiCaprio
419     Horror          8.0   William Friedkin      Ellen Burstyn
691    Western          7.8     Clint Eastwood     Clint Eastwood

     No_of_Votes        Gross  Metascore
6        1826188  107928762.0       94.0
10       1661481  315544750.0       92.0
17        918088  112000000.0       83.0
35        760360   13182281.0       57.0
52        167839      19181.0       99.0
56        194838    5017246.0       79.0
110       231855   11487676.0       86.0
145      1129894  128012934.0       63.0
419       362393  232906145.0       81.0
691        65659   31800000.0       69.0
                                          Series_Title Released_Year  Runtime  \
6                                         Pulp Fiction          1994      154
10   The Lord of the Rings: The Fellowship of the Ring          2001      178
17                     One Flew Over the Cuckoo's Nest          1975      133
35                                    The Intouchables          2011      112
52                                         City Lights          1931       87
56                                      Kimi no na wa.          2016      106
110                                           Das Boot          1981      149
145                                     Shutter Island          2010      138
419                                       The Exorcist          1973      122
691                             The Outlaw Josey Wales          1976      135

         Genre  IMDB_Rating           Director              Star1  \
6        Crime          8.9  Quentin Tarantino      John Travolta
10      Action          8.8      Peter Jackson        Elijah Wood
17       Drama          8.7       Milos Forman     Jack Nicholson
35   Biography          8.5    Olivier Nakache      Éric Toledano
52      Comedy          8.5    Charles Chaplin    Charles Chaplin
56   Animation          8.4     Makoto Shinkai   Ryûnosuke Kamiki
110  Adventure          8.3  Wolfgang Petersen    Jürgen Prochnow
145    Mystery          8.2    Martin Scorsese  Leonardo DiCaprio
419     Horror          8.0   William Friedkin      Ellen Burstyn
691    Western          7.8     Clint Eastwood     Clint Eastwood

     No_of_Votes        Gross  Metascore
6        1826188  107928762.0       94.0
10       1661481  315544750.0       92.0
17        918088  112000000.0       83.0
35        760360   13182281.0       57.0
52        167839      19181.0       99.0
56        194838    5017246.0       79.0
110       231855   11487676.0       86.0
145      1129894  128012934.0       63.0
419       362393  232906145.0       81.0
691        65659   31800000.0       69.0
                                          Series_Title Released_Year  Runtime  \
6                                         Pulp Fiction          1994      154
10   The Lord of the Rings: The Fellowship of the Ring          2001      178
17                     One Flew Over the Cuckoo's Nest          1975      133
35                                    The Intouchables          2011      112
52                                         City Lights          1931       87
56                                      Kimi no na wa.          2016      106
110                                           Das Boot          1981      149
145                                     Shutter Island          2010      138
419                                       The Exorcist          1973      122
691                             The Outlaw Josey Wales          1976      135

         Genre  IMDB_Rating           Director              Star1  \
6        Crime          8.9  Quentin Tarantino      John Travolta
10      Action          8.8      Peter Jackson        Elijah Wood
17       Drama          8.7       Milos Forman     Jack Nicholson
35   Biography          8.5    Olivier Nakache      Éric Toledano
52      Comedy          8.5    Charles Chaplin    Charles Chaplin
56   Animation          8.4     Makoto Shinkai   Ryûnosuke Kamiki
110  Adventure          8.3  Wolfgang Petersen    Jürgen Prochnow
145    Mystery          8.2    Martin Scorsese  Leonardo DiCaprio
419     Horror          8.0   William Friedkin      Ellen Burstyn
691    Western          7.8     Clint Eastwood     Clint Eastwood

     No_of_Votes        Gross  Metascore
6        1826188  107928762.0       94.0
10       1661481  315544750.0       92.0
17        918088  112000000.0       83.0
35        760360   13182281.0       57.0
52        167839      19181.0       99.0
56        194838    5017246.0       79.0
110       231855   11487676.0       86.0
145      1129894  128012934.0       63.0
419       362393  232906145.0       81.0
691        65659   31800000.0       69.0
                                          Series_Title Released_Year  Runtime  \
6                                         Pulp Fiction          1994      154
10   The Lord of the Rings: The Fellowship of the Ring          2001      178
17                     One Flew Over the Cuckoo's Nest          1975      133
35                                    The Intouchables          2011      112
52                                         City Lights          1931       87
56                                      Kimi no na wa.          2016      106
110                                           Das Boot          1981      149
145                                     Shutter Island          2010      138
419                                       The Exorcist          1973      122
691                             The Outlaw Josey Wales          1976      135

         Genre  IMDB_Rating           Director              Star1  \
6        Crime          8.9  Quentin Tarantino      John Travolta
10      Action          8.8      Peter Jackson        Elijah Wood
17       Drama          8.7       Milos Forman     Jack Nicholson
35   Biography          8.5    Olivier Nakache      Éric Toledano
52      Comedy          8.5    Charles Chaplin    Charles Chaplin
56   Animation          8.4     Makoto Shinkai   Ryûnosuke Kamiki
110  Adventure          8.3  Wolfgang Petersen    Jürgen Prochnow
145    Mystery          8.2    Martin Scorsese  Leonardo DiCaprio
419     Horror          8.0   William Friedkin      Ellen Burstyn
691    Western          7.8     Clint Eastwood     Clint Eastwood

     No_of_Votes        Gross  Metascore
6        1826188  107928762.0       94.0
10       1661481  315544750.0       92.0
17        918088  112000000.0       83.0
35        760360   13182281.0       57.0
52        167839      19181.0       99.0
56        194838    5017246.0       79.0
110       231855   11487676.0       86.0
145      1129894  128012934.0       63.0
419       362393  232906145.0       81.0
691        65659   31800000.0       69.0
                                          Series_Title Released_Year  Runtime  \
6                                         Pulp Fiction          1994      154
10   The Lord of the Rings: The Fellowship of the Ring          2001      178
17                     One Flew Over the Cuckoo's Nest          1975      133
35                                    The Intouchables          2011      112
52                                         City Lights          1931       87
56                                      Kimi no na wa.          2016      106
110                                           Das Boot          1981      149
145                                     Shutter Island          2010      138
419                                       The Exorcist          1973      122
691                             The Outlaw Josey Wales          1976      135

         Genre  IMDB_Rating           Director              Star1  \
6        Crime          8.9  Quentin Tarantino      John Travolta
10      Action          8.8      Peter Jackson        Elijah Wood
17       Drama          8.7       Milos Forman     Jack Nicholson
35   Biography          8.5    Olivier Nakache      Éric Toledano
52      Comedy          8.5    Charles Chaplin    Charles Chaplin
56   Animation          8.4     Makoto Shinkai   Ryûnosuke Kamiki
110  Adventure          8.3  Wolfgang Petersen    Jürgen Prochnow
145    Mystery          8.2    Martin Scorsese  Leonardo DiCaprio
419     Horror          8.0   William Friedkin      Ellen Burstyn
691    Western          7.8     Clint Eastwood     Clint Eastwood

     No_of_Votes        Gross  Metascore
6        1826188  107928762.0       94.0
10       1661481  315544750.0       92.0
17        918088  112000000.0       83.0
35        760360   13182281.0       57.0
52        167839      19181.0       99.0
56        194838    5017246.0       79.0
110       231855   11487676.0       86.0
145      1129894  128012934.0       63.0
419       362393  232906145.0       81.0
691        65659   31800000.0       69.0
                                          Series_Title Released_Year  Runtime  \
6                                         Pulp Fiction          1994      154
10   The Lord of the Rings: The Fellowship of the Ring          2001      178
17                     One Flew Over the Cuckoo's Nest          1975      133
35                                    The Intouchables          2011      112
52                                         City Lights          1931       87
56                                      Kimi no na wa.          2016      106
110                                           Das Boot          1981      149
145                                     Shutter Island          2010      138
419                                       The Exorcist          1973      122
691                             The Outlaw Josey Wales          1976      135

         Genre  IMDB_Rating           Director              Star1  \
6        Crime          8.9  Quentin Tarantino      John Travolta
10      Action          8.8      Peter Jackson        Elijah Wood
17       Drama          8.7       Milos Forman     Jack Nicholson
35   Biography          8.5    Olivier Nakache      Éric Toledano
52      Comedy          8.5    Charles Chaplin    Charles Chaplin
56   Animation          8.4     Makoto Shinkai   Ryûnosuke Kamiki
110  Adventure          8.3  Wolfgang Petersen    Jürgen Prochnow
145    Mystery          8.2    Martin Scorsese  Leonardo DiCaprio
419     Horror          8.0   William Friedkin      Ellen Burstyn
691    Western          7.8     Clint Eastwood     Clint Eastwood

     No_of_Votes        Gross  Metascore
6        1826188  107928762.0       94.0
10       1661481  315544750.0       92.0
17        918088  112000000.0       83.0
35        760360   13182281.0       57.0
52        167839      19181.0       99.0
56        194838    5017246.0       79.0
110       231855   11487676.0       86.0
145      1129894  128012934.0       63.0
419       362393  232906145.0       81.0
691        65659   31800000.0       69.0
                                          Series_Title Released_Year  Runtime  \
6                                         Pulp Fiction          1994      154
10   The Lord of the Rings: The Fellowship of the Ring          2001      178
17                     One Flew Over the Cuckoo's Nest          1975      133
35                                    The Intouchables          2011      112
52                                         City Lights          1931       87
56                                      Kimi no na wa.          2016      106
110                                           Das Boot          1981      149
145                                     Shutter Island          2010      138
419                                       The Exorcist          1973      122
691                             The Outlaw Josey Wales          1976      135

         Genre  IMDB_Rating           Director              Star1  \
6        Crime          8.9  Quentin Tarantino      John Travolta
10      Action          8.8      Peter Jackson        Elijah Wood
17       Drama          8.7       Milos Forman     Jack Nicholson
35   Biography          8.5    Olivier Nakache      Éric Toledano
52      Comedy          8.5    Charles Chaplin    Charles Chaplin
56   Animation          8.4     Makoto Shinkai   Ryûnosuke Kamiki
110  Adventure          8.3  Wolfgang Petersen    Jürgen Prochnow
145    Mystery          8.2    Martin Scorsese  Leonardo DiCaprio
419     Horror          8.0   William Friedkin      Ellen Burstyn
691    Western          7.8     Clint Eastwood     Clint Eastwood

     No_of_Votes        Gross  Metascore
6        1826188  107928762.0       94.0
10       1661481  315544750.0       92.0
17        918088  112000000.0       83.0
35        760360   13182281.0       57.0
52        167839      19181.0       99.0
56        194838    5017246.0       79.0
110       231855   11487676.0       86.0
145      1129894  128012934.0       63.0
419       362393  232906145.0       81.0
691        65659   31800000.0       69.0
                                          Series_Title Released_Year  Runtime  \
6                                         Pulp Fiction          1994      154
10   The Lord of the Rings: The Fellowship of the Ring          2001      178
17                     One Flew Over the Cuckoo's Nest          1975      133
35                                    The Intouchables          2011      112
52                                         City Lights          1931       87
56                                      Kimi no na wa.          2016      106
110                                           Das Boot          1981      149
145                                     Shutter Island          2010      138
419                                       The Exorcist          1973      122
691                             The Outlaw Josey Wales          1976      135

         Genre  IMDB_Rating           Director              Star1  \
6        Crime          8.9  Quentin Tarantino      John Travolta
10      Action          8.8      Peter Jackson        Elijah Wood
17       Drama          8.7       Milos Forman     Jack Nicholson
35   Biography          8.5    Olivier Nakache      Éric Toledano
52      Comedy          8.5    Charles Chaplin    Charles Chaplin
56   Animation          8.4     Makoto Shinkai   Ryûnosuke Kamiki
110  Adventure          8.3  Wolfgang Petersen    Jürgen Prochnow
145    Mystery          8.2    Martin Scorsese  Leonardo DiCaprio
419     Horror          8.0   William Friedkin      Ellen Burstyn
691    Western          7.8     Clint Eastwood     Clint Eastwood

     No_of_Votes        Gross  Metascore
6        1826188  107928762.0       94.0
10       1661481  315544750.0       92.0
17        918088  112000000.0       83.0
35        760360   13182281.0       57.0
52        167839      19181.0       99.0
56        194838    5017246.0       79.0
110       231855   11487676.0       86.0
145      1129894  128012934.0       63.0
419       362393  232906145.0       81.0
691        65659   31800000.0       69.0
                                          Series_Title Released_Year  Runtime  \
6                                         Pulp Fiction          1994      154
10   The Lord of the Rings: The Fellowship of the Ring          2001      178
17                     One Flew Over the Cuckoo's Nest          1975      133
35                                    The Intouchables          2011      112
52                                         City Lights          1931       87
56                                      Kimi no na wa.          2016      106
110                                           Das Boot          1981      149
145                                     Shutter Island          2010      138
419                                       The Exorcist          1973      122
691                             The Outlaw Josey Wales          1976      135

         Genre  IMDB_Rating           Director              Star1  \
6        Crime          8.9  Quentin Tarantino      John Travolta
10      Action          8.8      Peter Jackson        Elijah Wood
17       Drama          8.7       Milos Forman     Jack Nicholson
35   Biography          8.5    Olivier Nakache      Éric Toledano
52      Comedy          8.5    Charles Chaplin    Charles Chaplin
56   Animation          8.4     Makoto Shinkai   Ryûnosuke Kamiki
110  Adventure          8.3  Wolfgang Petersen    Jürgen Prochnow
145    Mystery          8.2    Martin Scorsese  Leonardo DiCaprio
419     Horror          8.0   William Friedkin      Ellen Burstyn
691    Western          7.8     Clint Eastwood     Clint Eastwood


##### apply()
this follow split,apply and combine approach

In [26]:
genre['IMDB_Rating'].apply(max)

Genre
Action       9.0
Adventure    8.6
Animation    8.6
Biography    8.9
Comedy       8.6
Crime        9.2
Drama        9.3
Family       7.8
Fantasy      8.1
Film-Noir    8.1
Horror       8.5
Mystery      8.4
Thriller     7.8
Western      8.8
Name: IMDB_Rating, dtype: float64

In [27]:
# find number of movies starting with A for each group
genre.apply(lambda x: (x['Series_Title'].str.startswith('A')).sum()) # str is applicable only on Series not DataFrames

Genre
Action       10
Adventure     2
Animation     2
Biography     9
Comedy       14
Crime         4
Drama        21
Family        0
Fantasy       0
Film-Noir     0
Horror        1
Mystery       0
Thriller      0
Western       0
dtype: int64

In [28]:
# find ranking of each movie in the group according to IMDB score
def ranking(group):
    group['Rank']=group["IMDB_Rating"].rank(ascending=False)
    return group
genre.apply(ranking)

                                                   Series_Title Released_Year  \
Genre
Action   2                                      The Dark Knight          2008
         5        The Lord of the Rings: The Return of the King          2003
         8                                            Inception          2010
         10   The Lord of the Rings: The Fellowship of the Ring          2001
         13               The Lord of the Rings: The Two Towers          2002
...                                                         ...           ...
Thriller 700                                    Wait Until Dark          1967
Western  12                     Il buono, il brutto, il cattivo          1966
         48                        Once Upon a Time in the West          1968
         115                         Per qualche dollaro in più          1965
         691                             The Outlaw Josey Wales          1976

              Runtime  IMDB_Rating           Director              Star1  \
Genre
Action   2        152          9.0  Christopher Nolan     Christian Bale
         5        201          8.9      Peter Jackson        Elijah Wood
         8        148          8.8  Christopher Nolan  Leonardo DiCaprio
         10       178          8.8      Peter Jackson        Elijah Wood
         13       179          8.7      Peter Jackson        Elijah Wood
...               ...          ...                ...                ...
Thriller 700      108          7.8      Terence Young     Audrey Hepburn
Western  12       161          8.8       Sergio Leone     Clint Eastwood
         48       165          8.5       Sergio Leone        Henry Fonda
         115      132          8.3       Sergio Leone     Clint Eastwood
         691      135          7.8     Clint Eastwood     Clint Eastwood

              No_of_Votes        Gross  Metascore  Rank
Genre
Action   2        2303232  534858444.0       84.0   1.0
         5        1642758  377845905.0       94.0   2.0
         8        2067042  292576195.0       74.0   3.5
         10       1661481  315544750.0       92.0   3.5
         13       1485555  342551365.0       87.0   6.0
...                   ...          ...        ...   ...
Thriller 700        27733   17550741.0       81.0   1.0
Western  12        688390    6100000.0       90.0   1.0
         48        302844    5321508.0       80.0   2.0
         115       232772   15000000.0       74.0   3.0
         691        65659   31800000.0       69.0   4.0

[1000 rows x 10 columns]

In [29]:
# find normalized IMDB rating group wise
genre.apply(lambda x:(x["IMDB_Rating"]-x["IMDB_Rating"].min())/(x["IMDB_Rating"].max()-x["IMDB_Rating"].min()))

Genre
Action    2      1.000000
          5      0.928571
          8      0.857143
          10     0.857143
          13     0.785714
                   ...
Thriller  700         NaN
Western   12     1.000000
          48     0.700000
          115    0.500000
          691    0.000000
Name: IMDB_Rating, Length: 1000, dtype: float64

##### groupby() on multiple cols

In [30]:
duo=movies.groupby(['Star1','Director'])
duo.get_group(('Aamir Khan', 'Nitesh Tiwari'))
print(duo.size())
duo.get_group(('Christian Bale','Christopher Nolan'))

Star1                 Director
Aamir Khan            Ashutosh Gowariker      1
                      Farhan Akhtar           1
                      Nitesh Tiwari           1
                      Rajkumar Hirani         2
                      Rajkumar Santoshi       1
                                             ..
Zbigniew Zamachowski  Krzysztof Kieslowski    1
Zooey Deschanel       Marc Webb               1
Çetin Tekindor        Çagan Irmak             1
Éric Toledano         Olivier Nakache         1
Ömer Faruk Sorak      Yilmaz Erdogan          1
Length: 898, dtype: int64

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
2,The Dark Knight,2008,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
36,The Prestige,2006,130,Drama,8.5,Christopher Nolan,Christian Bale,1190259,53089891.0,66.0
63,The Dark Knight Rises,2012,164,Action,8.4,Christopher Nolan,Christian Bale,1516346,448139099.0,78.0
155,Batman Begins,2005,140,Action,8.2,Christopher Nolan,Christian Bale,1308302,206852432.0,70.0

In [31]:
list(duo.groups)

[('Aamir Khan', 'Ashutosh Gowariker'),
 ('Aamir Khan', 'Farhan Akhtar'),
 ('Aamir Khan', 'Nitesh Tiwari'),
 ('Aamir Khan', 'Rajkumar Hirani'),
 ('Aamir Khan', 'Rajkumar Santoshi'),
 ('Aamir Khan', 'Rakeysh Omprakash Mehra'),
 ('Aaron Taylor-Johnson', 'Matthew Vaughn'),
 ('Abhay Deol', 'Anurag Kashyap'),
 ('Abraham Attah', 'Cary Joji Fukunaga'),
 ('Adam Driver', 'Noah Baumbach'),
 ('Adrian Molina', 'Lee Unkrich'),
 ('Adrien Brody', 'Roman Polanski'),
 ('Adrien Brody', 'Tony Kaye'),
 ('Ajay Devgn', 'Nishikant Kamat'),
 ('Akshay Kumar', 'Neeraj Pandey'),
 ('Akshay Kumar', 'Priyadarshan'),
 ('Akshay Kumar', 'Raja Menon'),
 ('Al Pacino', 'Brian De Palma'),
 ('Al Pacino', 'Francis Ford Coppola'),
 ('Al Pacino', 'James Foley'),
 ('Al Pacino', 'Martin Brest'),
 ('Al Pacino', 'Michael Mann'),
 ('Al Pacino', 'Mike Newell'),
 ('Al Pacino', 'Sidney Lumet'),
 ('Alain Delon', 'Jean-Pierre Melville'),
 ('Alan Mak', 'Andrew Lau'),
 ('Alec Guinness', 'Alexander Mackendrick'),
 ('Alejandro Jodorowsky', 'Alejandro Jodorowsky'),
 ('Aleksandr Antonov', 'Sergei M. Eisenstein'),
 ('Aleksey Kravchenko', 'Elem Klimov'),
 ('Aleksey Serebryakov', 'Andrey Zvyagintsev'),
 ('Alia Bhatt', 'Meghna Gulzar'),
 ('Alicia Vikander', 'Alex Garland'),
 ('Alisa Freyndlikh', 'Andrei Tarkovsky'),
 ('Amit Sadh', 'Abhishek Kapoor'),
 ('Amitabh Bachchan', 'Sanjay Leela Bhansali'),
 ('Amole Gupte', 'Aamir Khan'),
 ('Amy Adams', 'Denis Villeneuve'),
 ('Amy Poehler', 'Hiromasa Yonebayashi'),
 ('Anamaria Marinca', 'Cristian Mungiu'),
 ('Anand Gandhi', 'Rahi Anil Barve'),
 ('Anatoliy Solonitsyn', 'Andrei Tarkovsky'),
 ('Andie MacDowell', 'Robert Altman'),
 ('Andreas Wilson', 'Mikael Håfström'),
 ('Andrew Garfield', 'Mel Gibson'),
 ('Andrew Marton', 'Ken Annakin'),
 ('Andrew Philpot', 'Yoshiaki Kawajiri'),
 ('Angelina Jolie', 'Clint Eastwood'),
 ('Anna Karina', 'Jean-Luc Godard'),
 ('Anne Dorval', 'Xavier Dolan'),
 ('Ansel Elgort', 'Edgar Wright'),
 ('Anthony Hopkins', 'David Lynch'),
 ('Anthony Hopkins', 'James Ivory'),
 ('Anthony Hopkins', 'Roger Donaldson'),
 ('Anthony Perkins', 'Alfred Hitchcock'),
 ('Anthony Quinn', 'Federico Fellini'),
 ('Anthony Quinn', 'Moustapha Akkad'),
 ('Antonio Banderas', 'Pedro Almodóvar'),
 ('Anupam Kher', 'Neeraj Pandey'),
 ('Aoi Miyazaki', 'Mamoru Hosoda'),
 ('Aras Bulut Iynemli', 'Mehmet Ada Öztekin'),
 ('Armie Hammer', 'Luca Guadagnino'),
 ('Arnold Schwarzenegger', 'James Cameron'),
 ('Arnold Schwarzenegger', 'John McTiernan'),
 ('Arthur Rosson', 'Howard Hawks'),
 ('Asa Butterfield', 'Mark Herman'),
 ('Ash Brannon', 'John Lasseter'),
 ('Atsuko Tanaka', 'Mamoru Oshii'),
 ('Audrey Hepburn', 'Blake Edwards'),
 ('Audrey Hepburn', 'George Cukor'),
 ('Audrey Hepburn', 'Terence Young'),
 ('Audrey Tautou', 'Jean-Pierre Jeunet'),
 ('Ayushmann Khurrana', 'Amit Ravindernath Sharma'),
 ('Ayushmann Khurrana', 'Shoojit Sircar'),
 ('Ayushmann Khurrana', 'Sriram Raghavan'),
 ('Bajram Severdzan', 'Emir Kusturica'),
 ('Baki Davrak', 'Fatih Akin'),
 ('Barry Bostwick', 'René Laloux'),
 ('Barry Cook', 'Tony Bancroft'),
 ('Ben Affleck', 'Ben Affleck'),
 ('Ben Affleck', 'David Fincher'),
 ('Ben Burtt', 'Andrew Stanton'),
 ('Ben Kingsley', 'Richard Attenborough'),
 ('Ben Whishaw', 'Paul King'),
 ('Benedict Cumberbatch', 'Morten Tyldum'),
 ('Bernard-Pierre Donnadieu', 'George Sluizer'),
 ('Bertil Guve', 'Ingmar Bergman'),
 ('Bette Davis', 'Joseph L. Mankiewicz'),
 ('Bette Davis', 'Robert Aldrich'),
 ('Bibi Andersson', 'Ingmar Bergman'),
 ('Bill Murray', 'Harold Ramis'),
 ('Bill Murray', 'Ivan Reitman'),
 ('Bill Murray', 'Sofia Coppola'),
 ('Bill Nighy', 'Matthew Warchus'),
 ('Bill Pullman', 'David Lynch'),
 ('Billy Bob Thornton', 'Billy Bob Thornton'),
 ('Billy Crudup', 'Cameron Crowe'),
 ('Billy Crystal', 'Rob Reiner'),
 ('Birol Ünel', 'Fatih Akin'),
 ('Björk', 'Lars von Trier'),
 ('Bob Geldof', 'Alan Parker'),
 ('Bob Hoskins', 'Robert Zemeckis'),
 ('Bob Peterson', 'Pete Docter'),
 ('Boris Karloff', 'James Whale'),
 ('Boyd Kirkland', 'Kevin Altieri'),
 ('Brad Davis', 'Alan Parker'),
 ('Brad Pitt', 'Bennett Miller'),
 ('Brad Pitt', 'David Fincher'),
 ('Brad Pitt', 'Quentin Tarantino'),
 ('Bradley Cooper', 'David O. Russell'),
 ('Brady Corbet', 'Gregg Araki'),
 ('Brahim Hadjadj', 'Gillo Pontecorvo'),
 ('Branko Djuric', 'Danis Tanovic'),
 ("Brian O'Halloran", 'Kevin Smith'),
 ('Brie Larson', 'Destin Daniel Cretton'),
 ('Brie Larson', 'Lenny Abrahamson'),
 ('Brigitte Helm', 'Fritz Lang'),
 ('Brigitte Lin', 'Kar-Wai Wong'),
 ('Brooklynn Prince', 'Sean Baker'),
 ('Bruce Campbell', 'Sam Raimi'),
 ('Bruce Dern', 'Alexander Payne'),
 ('Bruce Lee', 'Robert Clouse'),
 ('Bruce Willis', 'John McTiernan'),
 ('Bruce Willis', 'Luc Besson'),
 ('Bruce Willis', 'M. Night Shyamalan'),
 ('Bruce Willis', 'Terry Gilliam'),
 ('Bruno Ganz', 'Oliver Hirschbiegel'),
 ('Bruno Ganz', 'Wim Wenders'),
 ('Bryan Cranston', 'Wes Anderson'),
 ('Burt Lancaster', 'Alexander Mackendrick'),
 ('Burt Lancaster', 'Fred Zinnemann'),
 ('Buster Keaton', 'Buster Keaton'),
 ('Buster Keaton', 'Clyde Bruckman'),
 ('Byron Howard', 'Nathan Greno'),
 ('Bérénice Bejo', 'Asghar Farhadi'),
 ('Carice van Houten', 'Paul Verhoeven'),
 ('Carlos Martínez López', 'Sergio Pablos'),
 ('Carole Lombard', 'Ernst Lubitsch'),
 ('Cary Elwes', 'James Wan'),
 ('Cary Elwes', 'Rob Reiner'),
 ('Cary Grant', 'Alfred Hitchcock'),
 ('Cary Grant', 'Frank Capra'),
 ('Cary Grant', 'George Cukor'),
 ('Cary Grant', 'Howard Hawks'),
 ('Cary Grant', 'Stanley Donen'),
 ('Casey Affleck', 'Kenneth Lonergan'),
 ('Cate Blanchett', 'Hayao Miyazaki'),
 ('Catherine Deneuve', 'Luis Buñuel'),
 ('Catherine Deneuve', 'Roman Polanski'),
 ('Cecilia Roth', 'Pedro Almodóvar'),
 ('Celia Johnson', 'David Lean'),
 ('Cem Yilmaz', 'Ömer Faruk Sorak'),
 ('Charles Chaplin', 'Charles Chaplin'),
 ('Charlie Cox', 'Matthew Vaughn'),
 ('Charlie Sheen', 'Oliver Stone'),
 ('Charlize Theron', 'Travis Knight'),
 ('Charlton Heston', 'Cecil B. DeMille'),
 ('Charlton Heston', 'Franklin J. Schaffner'),
 ('Charlton Heston', 'Orson Welles'),
 ('Charlton Heston', 'William Wyler'),
 ('Chieko Baishô', 'Hayao Miyazaki'),
 ('Chishû Ryû', 'Yasujirô Ozu'),
 ('Chiwetel Ejiofor', 'Steve McQueen'),
 ('Chloë Grace Moretz', 'Isao Takahata'),
 ('Choi Min-sik', 'Chan-wook Park'),
 ('Chris Evans', 'Marc Webb'),
 ('Chris Hemsworth', 'Taika Waititi'),
 ('Chris Pine', 'David Mackenzie'),
 ('Chris Pine', 'J.J. Abrams'),
 ('Chris Pratt', 'James Gunn'),
 ('Chris Renaud', 'Pierre Coffin'),
 ('Chris Sanders', 'Dean DeBlois'),
 ('Chris Williams', 'Don Hall'),
 ('Christian Bale', 'Adam McKay'),
 ('Christian Bale', 'Brad Anderson'),
 ('Christian Bale', 'Christopher Nolan'),
 ('Christian Bale', 'Mary Harron'),
 ('Christian Bale', 'Steven Spielberg'),
 ('Christian Friedel', 'Michael Haneke'),
 ('Christian Slater', 'Tony Scott'),
 ('Cillian Murphy', 'Danny Boyle'),
 ('Clark Gable', 'Frank Capra'),
 ('Claude Rains', 'James Whale'),
 ('Cleavon Little', 'Mel Brooks'),
 ('Clint Eastwood', 'Brian G. Hutton'),
 ('Clint Eastwood', 'Clint Eastwood'),
 ('Clint Eastwood', 'Don Siegel'),
 ('Clint Eastwood', 'Sergio Leone'),
 ('Colin Clive', 'James Whale'),
 ('Colin Farrell', 'Martin McDonagh'),
 ('Colin Firth', 'Matthew Vaughn'),
 ('Colin Firth', 'Tom Hooper'),
 ('Craig T. Nelson', 'Brad Bird'),
 ('Cuba Gooding Jr.', 'John Singleton'),
 ('Daisy Ridley', 'J.J. Abrams'),
 ('Dakota Fanning', 'Henry Selick'),
 ('Damian Chapa', 'Taylor Hackford'),
 ('Daniel Brühl', 'Ron Howard'),
 ('Daniel Brühl', 'Wolfgang Becker'),
 ('Daniel Craig', 'David Fincher'),
 ('Daniel Craig', 'Martin Campbell'),
 ('Daniel Craig', 'Rian Johnson'),
 ('Daniel Craig', 'Sam Mendes'),
 ('Daniel Day-Lewis', 'Jim Sheridan'),
 ('Daniel Day-Lewis', 'Michael Mann'),
 ('Daniel Day-Lewis', 'Paul Thomas Anderson'),
 ('Daniel Kaluuya', 'Jordan Peele'),
 ('Daniel Radcliffe', 'Alfonso Cuarón'),
 ('Daniel Radcliffe', 'Chris Columbus'),
 ('Daniel Radcliffe', 'David Yates'),
 ('Daniel Radcliffe', 'Mike Newell'),
 ('Danny Aiello', 'Spike Lee'),
 ('Danny Elfman', 'Henry Selick'),
 ('Danny Glover', 'Steven Spielberg'),
 ('Darío Grandinetti', 'Damián Szifron'),
 ('Daveigh Chase', 'Hayao Miyazaki'),
 ('David Emge', 'George A. Romero'),
 ('David Hemmings', 'Michelangelo Antonioni'),
 ('David Lee Smith', 'Richard Schenkman'),
 ('David Rawle', 'Tomm Moore'),
 ('David Silverman', 'Pete Docter'),
 ('David Thewlis', 'Mike Leigh'),
 ('David Zucker', 'Jim Abrahams'),
 ('Davor Dujmovic', 'Emir Kusturica'),
 ('Dean-Charles Chapman', 'Sam Mendes'),
 ('Deborah Kerr', 'Jack Clayton'),
 ('Dennis Price', 'Robert Hamer'),
 ('Denzel Washington', 'Antoine Fuqua'),
 ('Denzel Washington', 'Boaz Yakin'),
 ('Denzel Washington', 'Norman Jewison'),
 ('Denzel Washington', 'Ridley Scott'),
 ('Denzel Washington', 'Spike Lee'),
 ('Denzel Washington', 'Tony Scott'),
 ('Dev Patel', 'Garth Davis'),
 ('Diane Kruger', 'Christian Carion'),
 ('Domhnall Gleeson', 'Richard Curtis'),
 ('Don Cheadle', 'Paul Haggis'),
 ('Don Cheadle', 'Terry George'),
 ('Donald Pleasence', 'John Carpenter'),
 ('Donald Sutherland', 'Robert Redford'),
 ('Donnie Yen', 'Wilson Yip'),
 ('Duane Jones', 'George A. Romero'),
 ('Dustin Hoffman', 'Alan J. Pakula'),
 ('Dustin Hoffman', 'Barry Levinson'),
 ('Dustin Hoffman', 'John Schlesinger'),
 ('Dustin Hoffman', 'Mike Nichols'),
 ('Dustin Hoffman', 'Robert Benton'),
 ('Eddie Redmayne', 'Aaron Sorkin'),
 ('Eddie Redmayne', 'James Marsh'),
 ('Edmund Goulding', 'Sam Wood'),
 ('Edmund Gwenn', 'George Seaton'),
 ('Eduard Abalov', 'Andrei Tarkovsky'),
 ('Eduardo Noriega', 'Alejandro Amenábar'),
 ('Edward Fox', 'Fred Zinnemann'),
 ('Edward Norton', 'Neil Burger'),
 ('Edward Norton', 'Spike Lee'),
 ('Edward Norton', 'Tony Kaye'),
 ('Eileen Walsh', 'Peter Mullan'),
 ('Eli Marienthal', 'Brad Bird'),
 ('Elijah Wood', 'Peter Jackson'),
 ('Elizabeth Taylor', 'George Stevens'),
 ('Elizabeth Taylor', 'Mike Nichols'),
 ('Elizabeth Taylor', 'Richard Brooks'),
 ('Ellar Coltrane', 'Richard Linklater'),
 ('Ellen Burstyn', 'Darren Aronofsky'),
 ('Ellen Burstyn', 'William Friedkin'),
 ('Elliott Gould', 'Robert Altman'),
 ('Emeric Pressburger', 'Michael Powell'),
 ('Emile Hirsch', 'Sean Penn'),
 ('Emilio Echevarría', 'Alejandro G. Iñárritu'),
 ('Emilio Estevez', 'John Hughes'),
 ('Emily Blunt', 'Denis Villeneuve'),
 ('Emily Watson', 'Lars von Trier'),
 ('Emma Stone', 'Tate Taylor'),
 ('Emma Thompson', 'Ang Lee'),
 ('Emmanuelle Riva', 'Alain Resnais'),
 ('Erdem Can', 'Can Ulkay'),
 ('Erdem Can', 'Levent Semerci'),
 ('Ernest B. Schoedsack', 'Merian C. Cooper'),
 ('Ethan Coen', 'Joel Coen'),
 ('Ethan Hawke', 'Andrew Niccol'),
 ('Ethan Hawke', 'Richard Linklater'),
 ('Ewan McGregor', 'Danny Boyle'),
 ('Ewan McGregor', 'Tim Burton'),
 ('F. Murray Abraham', 'Milos Forman'),
 ('Farhan Akhtar', 'Rakeysh Omprakash Mehra'),
 ('Farley Granger', 'Alfred Hitchcock'),
 ('Faye Dunaway', 'Sidney Lumet'),
 ('Felicity Jones', 'Gareth Edwards'),
 ('Ferdia Walsh-Peelo', 'John Carney'),
 ('Fernanda Montenegro', 'Walter Salles'),
 ('Fernando Rey', 'Luis Buñuel'),
 ('Fionn Whitehead', 'Christopher Nolan'),
 ('Frances McDormand', 'Martin McDonagh'),
 ('Frank Langella', 'Ron Howard'),
 ('Frank Sinatra', 'John Frankenheimer'),
 ('Franka Potente', 'Doug Liman'),
 ('Franka Potente', 'Tom Tykwer'),
 ('Fred MacMurray', 'Billy Wilder'),
 ('Gabriele Ferzetti', 'Michelangelo Antonioni'),
 ('Gael García Bernal', 'Walter Salles'),
 ('Gary Cooper', 'Fred Zinnemann'),
 ('Gary Oldman', 'Matt Reeves'),
 ('Gaspard Manesse', 'Louis Malle'),
 ('Gena Rowlands', 'Nick Cassavetes'),
 ('Gene Hackman', 'Alan Parker'),
 ('Gene Hackman', 'Francis Ford Coppola'),
 ('Gene Hackman', 'Wes Anderson'),
 ('Gene Hackman', 'William Friedkin'),
 ('Gene Kelly', 'Stanley Donen'),
 ('Gene Tierney', 'Otto Preminger'),
 ('Gene Wilder', 'Mel Brooks'),
 ('Gene Wilder', 'Mel Stuart'),
 ('Geoffrey Rush', 'Giuseppe Tornatore'),
 ('Geoffrey Rush', 'Scott Hicks'),
 ('George C. Scott', 'Franklin J. Schaffner'),
 ('George Clooney', 'Steven Soderbergh'),
 ('George Clooney', 'Wes Anderson'),
 ('George Cukor', 'Victor Fleming'),
 ("George O'Brien", 'F.W. Murnau'),
 ('Gerard Butler', 'Zack Snyder'),
 ('Gerardo Taracena', 'Mel Gibson'),
 ('Giulietta Masina', 'Federico Fellini'),
 ('Giuseppe Battiston', 'Paolo Genovese'),
 ('Glen Hansard', 'John Carney'),
 ('Golshifteh Farahani', 'Asghar Farhadi'),
 ('Gong Li', 'Yimou Zhang'),
 ('Graham Chapman', 'Terry Jones'),
 ('Gregory Peck', 'J. Lee Thompson'),
 ('Gregory Peck', 'Robert Mulligan'),
 ('Gregory Peck', 'William Wyler'),
 ('Griffin Dunne', 'Martin Scorsese'),
 ('Groucho Marx', 'Leo McCarey'),
 ('Guillaume Canet', 'Yann Samuell'),
 ('Guy Pearce', 'Christopher Nolan'),
 ('Gérard Jugnot', 'Christophe Barratier'),
 ('Günes Sensoy', 'Deniz Gamze Ergüven'),
 ('Haluk Bilginer', 'Nuri Bilge Ceylan'),
 ('Harriet Andersson', 'Ingmar Bergman'),
 ('Harrison Ford', 'Andrew Davis'),
 ('Harrison Ford', 'Denis Villeneuve'),
 ('Harrison Ford', 'Ridley Scott'),
 ('Harrison Ford', 'Steven Spielberg'),
 ('Harry Dean Stanton', 'Wim Wenders'),
 ('Harvey Keitel', 'Quentin Tarantino'),
 ('Henry Fonda', 'John Ford'),
 ('Henry Fonda', 'Sergio Leone'),
 ('Henry Fonda', 'Sidney Lumet'),
 ('Henry Thomas', 'Steven Spielberg'),
 ('Hideaki Anno', 'Hayao Miyazaki'),
 ('Hilary Swank', 'Clint Eastwood'),
 ('Hiromasa Yonebayashi', 'James Simone'),
 ('Hitoshi Takagi', 'Hayao Miyazaki'),
 ('Hrithik Roshan', 'Zoya Akhtar'),
 ('Hugh Jackman', 'Denis Villeneuve'),
 ('Hugh Jackman', 'James Mangold'),
 ('Hugh Welchman', 'Dorota Kobiela'),
 ('Hugo Weaving', 'James McTeigue'),
 ('Humphrey Bogart', 'Billy Wilder'),
 ('Humphrey Bogart', 'Howard Hawks'),
 ('Humphrey Bogart', 'John Huston'),
 ('Humphrey Bogart', 'Michael Curtiz'),
 ('Humphrey Bogart', 'Nicholas Ray'),
 ('Hye-ja Kim', 'Bong Joon Ho'),
 ('Ian McKellen', 'Peter Jackson'),
 ('Iko Uwais', 'Gareth Evans'),
 ('Ingrid Bergman', 'Ingmar Bergman'),
 ('Irrfan Khan', 'Meghna Gulzar'),
 ('Irrfan Khan', 'Ritesh Batra'),
 ('Irrfan Khan', 'Tigmanshu Dhulia'),
 ('Irène Jacob', 'Krzysztof Kieslowski'),
 ('Isabella Rossellini', 'David Lynch'),
 ('Ivana Baquero', 'Guillermo del Toro'),
 ('J. Mackye Gruber', 'Eric Bress'),
 ('Jack Lemmon', 'Billy Wilder'),
 ('Jack Lemmon', 'Gene Saks'),
 ('Jack Nicholson', 'James L. Brooks'),
 ('Jack Nicholson', 'Milos Forman'),
 ('Jack Nicholson', 'Roman Polanski'),
 ('Jack Nicholson', 'Stanley Kubrick'),
 ('Jackie Earle Haley', 'Zack Snyder'),
 ('Jacob Tremblay', 'Stephen Chbosky'),
 ('Jake Gyllenhaal', 'Ang Lee'),
 ('Jake Gyllenhaal', 'Dan Gilroy'),
 ('Jake Gyllenhaal', 'David Ayer'),
 ('Jake Gyllenhaal', 'David Fincher'),
 ('Jake Gyllenhaal', 'Joe Johnston'),
 ('Jake Gyllenhaal', 'Richard Kelly'),
 ('James Caan', 'Rob Reiner'),
 ('James Cagney', 'Raoul Walsh'),
 ('James Dean', 'Elia Kazan'),
 ('James Dean', 'Nicholas Ray'),
 ('James Marsden', 'Bob Gale'),
 ('James McAvoy', 'Kevin Macdonald'),
 ('James McAvoy', 'Matthew Vaughn'),
 ('James Stewart', 'Alfred Hitchcock'),
 ('James Stewart', 'Frank Capra'),
 ('James Stewart', 'Henry Koster'),
 ('James Stewart', 'John Ford'),
 ('James Stewart', 'Otto Preminger'),
 ('Jamie Bell', 'Stephen Daldry'),
 ('Jamie Foxx', 'Quentin Tarantino'),
 ('Jamie Foxx', 'Taylor Hackford'),
 ('Jan Pinkava', 'Brad Bird'),
 ('Jane Adams', 'Todd Solondz'),
 ('Jang Dong-Gun', 'Je-kyu Kang'),
 ('Jared Gilman', 'Wes Anderson'),
 ('Jared Leto', 'Jaco Van Dormael'),
 ('Jason Flemyng', 'Guy Ritchie'),
 ('Jason London', 'Richard Linklater'),
 ('Jason Schwartzman', 'Wes Anderson'),
 ('Jason Statham', 'Guy Ritchie'),
 ('Javier Bardem', 'Alejandro Amenábar'),
 ('Jay Baruchel', 'Dean DeBlois'),
 ('Jean Dujardin', 'Michel Hazanavicius'),
 ('Jean Gabin', 'Jean Renoir'),
 ('Jean Reno', 'Luc Besson'),
 ('Jean Servais', 'Jules Dassin'),
 ('Jean-Louis Trintignant', 'Bernardo Bertolucci'),
 ('Jean-Louis Trintignant', 'Michael Haneke'),
 ('Jean-Paul Belmondo', 'Jean-Luc Godard'),
 ('Jean-Pierre Jeunet', 'Marc Caro'),
 ('Jean-Pierre Léaud', 'François Truffaut'),
 ('Jeanne Moreau', 'François Truffaut'),
 ('Jeff Bridges', 'Mark Osborne'),
 ('Jesse Eisenberg', 'David Fincher'),
 ('Jesse Eisenberg', 'Ruben Fleischer'),
 ('Jet Li', 'Ronny Yu'),
 ('Jet Li', 'Yimou Zhang'),
 ('Jim Carrey', 'Michel Gondry'),
 ('Jim Carrey', 'Peter Weir'),
 ('Jim Caviezel', 'Kevin Reynolds'),
 ('Jim Caviezel', 'Terrence Malick'),
 ('Jim Henson', 'James Frawley'),
 ('Joaquin Phoenix', 'James Mangold'),
 ('Joaquin Phoenix', 'Spike Jonze'),
 ('Joaquin Phoenix', 'Todd Phillips'),
 ('Jodie Foster', 'Jonathan Demme'),
 ('Joe Pesci', 'Jonathan Lynn'),
 ('Joe Russo', 'Anthony Russo'),
 ('Joel Coen', 'Ethan Coen'),
 ('John Belushi', 'John Landis'),
 ('John C. Reilly', 'Rich Moore'),
 ('John Cameron Mitchell', 'John Cameron Mitchell'),
 ('John Cho', 'Aneesh Chaganty'),
 ('John Cusack', 'Spike Jonze'),
 ('John Hubley', 'Martin Rosen'),
 ('John Lennon', 'Richard Lester'),
 ('John Lone', 'Bernardo Bertolucci'),
 ('John Musker', 'Ron Clements'),
 ('John Travolta', 'Quentin Tarantino'),
 ('John Wayne', 'Howard Hawks'),
 ('John Wayne', 'John Ford'),
 ('Johnny Depp', 'Gore Verbinski'),
 ('Johnny Depp', 'Jim Jarmusch'),
 ('Johnny Depp', 'Lasse Hallström'),
 ('Johnny Depp', 'Marc Forster'),
 ('Johnny Depp', 'Ted Demme'),
 ('Johnny Depp', 'Terry Gilliam'),
 ('Johnny Depp', 'Tim Burton'),
 ('Jon Voight', 'John Boorman'),
 ('Jonathan Pryce', 'Terry Gilliam'),
 ('Jose Coronado', 'Oriol Paulo'),
 ('Joseph Gordon-Levitt', 'Jonathan Levine'),
 ('Josh Brolin', 'Joseph Kosinski'),
 ('Josh Hartnett', 'Paul McGuigan'),
 ('Josh Hartnett', 'Ridley Scott'),
 ("Josh O'Connor", 'Francis Lee'),
 ('Jude Law', 'Jean-Jacques Annaud'),
 ('Judi Dench', 'Stephen Frears'),
 ('Julianne Moore', 'Alfonso Cuarón'),
 ('Julie Andrews', 'Robert Stevenson'),
 ('Julie Andrews', 'Robert Wise'),
 ('Juliette Binoche', 'Krzysztof Kieslowski'),
 ('Junko Iwao', 'Satoshi Kon'),
 ('Jürgen Prochnow', 'Wolfgang Petersen'),
 ('Jürgen Vogel', 'Dennis Gansel'),
 ('Kang-ho Song', 'Bong Joon Ho'),
 ('Kang-ho Song', 'Chan-wook Park'),
 ('Kangana Ranaut', 'Vikas Bahl'),
 ('Karlheinz Böhm', 'Michael Powell'),
 ('Katharine Hepburn', 'Howard Hawks'),
 ('Katharine Hepburn', 'Mark Rydell'),
 ('Kathy Bates', 'Jon Avnet'),
 ('Kazuya Tsurumaki', 'Hideaki Anno'),
 ('Keir Dullea', 'Stanley Kubrick'),
 ('Keira Knightley', 'Joe Wright'),
 ('Kelsey Asbille', 'Taylor Sheridan'),
 ('Kemp Powers', 'Pete Docter'),
 ('Ken Watanabe', 'Clint Eastwood'),
 ('Kenneth Branagh', 'Kenneth Branagh'),
 ('Kevin Costner', 'Brian De Palma'),
 ('Kevin Costner', 'Kevin Costner'),
 ('Kevin Costner', 'Oliver Stone'),
 ('Kevin Jarre', 'George P. Cosmatos'),
 ('Kevin McCarthy', 'Don Siegel'),
 ('Kevin Spacey', 'Bryan Singer'),
 ('Kevin Spacey', 'Curtis Hanson'),
 ('Kevin Spacey', 'Sam Mendes'),
 ('Ki-duk Kim', 'Ki-duk Kim'),
 ('Kim Min-hee', 'Chan-wook Park'),
 ('Kim Yoon-seok', 'Hong-jin Na'),
 ('Kirk Douglas', 'Billy Wilder'),
 ('Kirk Douglas', 'Stanley Kubrick'),
 ('Kirk Wise', 'Gary Trousdale'),
 ('Kirsten Dunst', 'Hayao Miyazaki'),
 ('Klaus Kinski', 'Werner Herzog'),
 ('Kurt Russell', 'John Carpenter'),
 ('Kátia Lund', 'Fernando Meirelles'),
 ('Kåre Hedebrant', 'Tomas Alfredson'),
 ('Kôichi Yamadera', 'Yoshiaki Kawajiri'),
 ('Lady Gaga', 'Bradley Cooper'),
 ('Laia Costa', 'Sebastian Schipper'),
 ('Lamberto Maggiorani', 'Vittorio De Sica'),
 ('Laura Obiols', 'Julian Schnabel'),
 ('Laura Obiols', 'Ken Loach'),
 ('Laurence Olivier', 'Alfred Hitchcock'),
 ('Laurence Olivier', 'Joseph L. Mankiewicz'),
 ('Lee Byung-Hun', 'Jee-woon Kim'),
 ('Lee Marvin', 'Robert Aldrich'),
 ('Lee Pace', 'Tarsem Singh'),
 ('Lee Unkrich', 'Andrew Stanton'),
 ('Lee Yeong-ae', 'Chan-wook Park'),
 ('Lembit Ulfsak', 'Zaza Urushadze'),
 ('Leon Lai', 'Kar-Wai Wong'),
 ('Leonardo DiCaprio', 'Alejandro G. Iñárritu'),
 ('Leonardo DiCaprio', 'Christopher Nolan'),
 ('Leonardo DiCaprio', 'Edward Zwick'),
 ('Leonardo DiCaprio', 'James Cameron'),
 ('Leonardo DiCaprio', 'Martin Scorsese'),
 ('Leonardo DiCaprio', 'Quentin Tarantino'),
 ('Leonardo DiCaprio', 'Steven Spielberg'),
 ('Leslie Cheung', 'Kaige Chen'),
 ('Leslie Nielsen', 'David Zucker'),

In [32]:
# find the most earning actor->director combo
duo['Gross'].sum().sort_values(ascending=False).head(1)

Star1           Director
Toshirô Mifune  Akira Kurosawa    2.999877e+09
Name: Gross, dtype: float64

In [33]:
# find the best(in-terms of metascore(avg)) actor->genre combo
movies.groupby(['Star1','Genre'])['Metascore'].mean().sort_values(ascending=False).head(10)

Star1            Genre
Bertil Guve      Drama        100.0
Orson Welles     Drama        100.0
Peter O'Toole    Adventure    100.0
Humphrey Bogart  Drama        100.0
Cary Grant       Drama        100.0
Ellar Coltrane   Drama        100.0
James Stewart    Mystery      100.0
Charlton Heston  Crime         99.0
Gene Kelly       Comedy        99.0
Robert Mitchum   Crime         99.0
Name: Metascore, dtype: float64

In [34]:
# agg on multiple groupby
duo.agg({"Gross":["min",'max','mean']})

                                                 Gross               \
                                                   min          max
Star1                Director
Aamir Khan           Ashutosh Gowariker        70147.0      70147.0
                     Farhan Akhtar            300000.0     300000.0
                     Nitesh Tiwari          12391761.0   12391761.0
                     Rajkumar Hirani         6532908.0   10616104.0
                     Rajkumar Santoshi     213351844.0  213351844.0
...                                                ...          ...
Zbigniew Zamachowski Krzysztof Kieslowski    1464625.0    1464625.0
Zooey Deschanel      Marc Webb              32391374.0   32391374.0
Çetin Tekindor       Çagan Irmak           461855363.0  461855363.0
Éric Toledano        Olivier Nakache        13182281.0   13182281.0
Ömer Faruk Sorak     Yilmaz Erdogan        200178699.0  200178699.0


                                                  mean
Star1                Director
Aamir Khan           Ashutosh Gowariker        70147.0
                     Farhan Akhtar            300000.0
                     Nitesh Tiwari          12391761.0
                     Rajkumar Hirani         8574506.0
                     Rajkumar Santoshi     213351844.0
...                                                ...
Zbigniew Zamachowski Krzysztof Kieslowski    1464625.0
Zooey Deschanel      Marc Webb              32391374.0
Çetin Tekindor       Çagan Irmak           461855363.0
Éric Toledano        Olivier Nakache        13182281.0
Ömer Faruk Sorak     Yilmaz Erdogan        200178699.0

[898 rows x 3 columns]

In [46]:
psl=pd.read_csv("~/Machine Learning/Pandas/Datasets/PSL.csv")
psl

,id,match_id,date,season,venue,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,extra_runs,total_runs,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder,winner,win_by,match_type,player_of_match,umpire_1,umpire_2
0,1,1075986,2017-02-09,2017,Dubai International Cricket Stadium,1,Peshawar Zalmi,Islamabad United,1,1,Mohammad Hafeez,Mohammad Irfan,DJ Malan,0,0,0,NaN,True,Mohammad Hafeez,caught,Sharjeel Khan,Islamabad United,wickets 7,regular,BJ Haddin,Ahsan Raza,Shozab Raza
1,2,1075986,2017-02-09,2017,Dubai International Cricket Stadium,1,Peshawar Zalmi,Islamabad United,1,2,Kamran Akmal,Mohammad Irfan,DJ Malan,1,0,1,NaN,False,NaN,NaN,NaN,Islamabad United,wickets 7,regular,BJ Haddin,Ahsan Raza,Shozab Raza
2,3,1075986,2017-02-09,2017,Dubai International Cricket Stadium,1,Peshawar Zalmi,Islamabad United,1,3,DJ Malan,Mohammad Irfan,Kamran Akmal,0,0,0,NaN,False,NaN,NaN,NaN,Islamabad United,wickets 7,regular,BJ Haddin,Ahsan Raza,Shozab Raza
3,4,1075986,2017-02-09,2017,Dubai International Cricket Stadium,1,Peshawar Zalmi,Islamabad United,1,4,DJ Malan,Mohammad Irfan,Kamran Akmal,0,0,0,NaN,False,NaN,NaN,NaN,Islamabad United,wickets 7,regular,BJ Haddin,Ahsan Raza,Shozab Raza
4,5,1075986,2017-02-09,2017,Dubai International Cricket Stadium,1,Peshawar Zalmi,Islamabad United,1,5,DJ Malan,Mohammad Irfan,Kamran Akmal,0,0,0,NaN,False,NaN,NaN,NaN,Islamabad United,wickets 7,regular,BJ Haddin,Ahsan Raza,Shozab Raza
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73779,541,959221,2016-02-23,2016,Dubai International Cricket Stadium,2,Islamabad United,Quetta Gladiators,18,6,BJ Haddin,Zulfiqar Babar,Khalid Latif,0,0,0,NaN,False,NaN,NaN,NaN,Islamabad United,wickets 6,final,DR Smith,JS Wilson,Aleem Dar
73780,542,959221,2016-02-23,2016,Dubai International Cricket Stadium,2,Islamabad United,Quetta Gladiators,19,1,Khalid Latif,Anwar Ali,BJ Haddin,4,0,4,NaN,False,NaN,NaN,NaN,Islamabad United,wickets 6,final,DR Smith,JS Wilson,Aleem Dar
73781,543,959221,2016-02-23,2016,Dubai International Cricket Stadium,2,Islamabad United,Quetta Gladiators,19,2,Khalid Latif,Anwar Ali,BJ Haddin,0,0,0,NaN,True,Khalid Latif,caught,Zulfiqar Babar,Islamabad United,wickets 6,final,DR Smith,JS Wilson,Aleem Dar
73782,544,959221,2016-02-23,2016,Dubai International Cricket Stadium,2,Islamabad United,Quetta Gladiators,19,3,BJ Haddin,Anwar Ali,Misbah-ul-Haq,1,0,1,NaN,False,NaN,NaN,NaN,Islamabad United,wickets 6,final,DR Smith,JS Wilson,Aleem Dar
73783,545,959221,2016-02-23,2016,Dubai International Cricket Stadium,2,Islamabad United,Quetta Gladiators,19,4,Misbah-ul-Haq,Anwar Ali,BJ Haddin,1,0,1,NaN,False,NaN,NaN,NaN,Islamabad United,wickets 6,final,DR Smith,JS Wilson,Aleem Dar

In [47]:
psl.head()

,id,match_id,date,season,venue,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,extra_runs,total_runs,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder,winner,win_by,match_type,player_of_match,umpire_1,umpire_2
0,1,1075986,2017-02-09,2017,Dubai International Cricket Stadium,1,Peshawar Zalmi,Islamabad United,1,1,Mohammad Hafeez,Mohammad Irfan,DJ Malan,0,0,0,NaN,True,Mohammad Hafeez,caught,Sharjeel Khan,Islamabad United,wickets 7,regular,BJ Haddin,Ahsan Raza,Shozab Raza
1,2,1075986,2017-02-09,2017,Dubai International Cricket Stadium,1,Peshawar Zalmi,Islamabad United,1,2,Kamran Akmal,Mohammad Irfan,DJ Malan,1,0,1,NaN,False,NaN,NaN,NaN,Islamabad United,wickets 7,regular,BJ Haddin,Ahsan Raza,Shozab Raza
2,3,1075986,2017-02-09,2017,Dubai International Cricket Stadium,1,Peshawar Zalmi,Islamabad United,1,3,DJ Malan,Mohammad Irfan,Kamran Akmal,0,0,0,NaN,False,NaN,NaN,NaN,Islamabad United,wickets 7,regular,BJ Haddin,Ahsan Raza,Shozab Raza
3,4,1075986,2017-02-09,2017,Dubai International Cricket Stadium,1,Peshawar Zalmi,Islamabad United,1,4,DJ Malan,Mohammad Irfan,Kamran Akmal,0,0,0,NaN,False,NaN,NaN,NaN,Islamabad United,wickets 7,regular,BJ Haddin,Ahsan Raza,Shozab Raza
4,5,1075986,2017-02-09,2017,Dubai International Cricket Stadium,1,Peshawar Zalmi,Islamabad United,1,5,DJ Malan,Mohammad Irfan,Kamran Akmal,0,0,0,NaN,False,NaN,NaN,NaN,Islamabad United,wickets 7,regular,BJ Haddin,Ahsan Raza,Shozab Raza

In [45]:
pd.set_option("display.max_columns",None)

In [49]:
# find the top 10 batsman in terms of runs
psl.groupby('batter')['batsman_runs'].sum().sort_values(ascending=False).head(10)

batter
Babar Azam         3792
Fakhar Zaman       2969
Mohammad Rizwan    2770
Shoaib Malik       2350
RR Rossouw         2292
Kamran Akmal       1942
Mohammad Hafeez    1672
C Munro            1633
Sarfraz Ahmed      1525
Shan Masood        1503
Name: batsman_runs, dtype: int64

In [55]:
# find the batsman with max no of sixes
six=psl[psl['batsman_runs']==6]
six.groupby('batter')['match_id'].count().sort_values(ascending=False).head(1)

batter
Fakhar Zaman    128
Name: match_id, dtype: int64

In [86]:
# find batsman with most number of 4's and 6's in last 5 overs
death_overs=psl[psl['over']>15]
death_batters=death_overs[(death_overs['batsman_runs']==6) | (death_overs['batsman_runs']==4)]
death_batters.groupby('batter')['match_id'].count().sort_values(ascending=False)

batter
Imad Wasim        104
Faheem Ashraf     102
Khushdil Shah      91
KA Pollard         90
Iftikhar Ahmed     87
                 ...
TS Mills            1
Umar Gul            1
Usman Tariq         1
Zahir Khan          1
Zohaib Khan         1
Name: match_id, Length: 248, dtype: int64

In [93]:
# find Babar Azam's record against all teams
bobzy=psl[psl['batter']=='Babar Azam']
bobzy.groupby('bowling_team')['batsman_runs'].count().sort_values(ascending=False)

bowling_team
Islamabad United     658
Lahore Qalandars     583
Multan Sultans       528
Quetta Gladiators    527
Peshawar Zalmi       516
Karachi Kings        244
Name: batsman_runs, dtype: int64

In [129]:
# Create a function that can return the highest score of any batsman
def highest_score(batsman):
    bt=psl[psl['batter']==batsman]
    return bt.groupby('match_id')['batsman_runs'].sum().sort_values(ascending=False).head(1).values[0]

highest_score('Imad Wasim')

np.int64(92)

np.int64(115)

,id,match_id,date,season,venue,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,extra_runs,total_runs,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder,winner,win_by,match_type,player_of_match,umpire_1,umpire_2
478,7,1075988,2017-02-10,2017,Dubai International Cricket Stadium,1,Karachi Kings,Peshawar Zalmi,1,5,Babar Azam,Mohammad Hafeez,CH Gayle,0,0,0,NaN,False,NaN,NaN,NaN,Peshawar Zalmi,wickets 7,regular,EJG Morgan,Ahmed Shahab,Ahsan Raza
479,8,1075988,2017-02-10,2017,Dubai International Cricket Stadium,1,Karachi Kings,Peshawar Zalmi,1,6,Babar Azam,Mohammad Hafeez,CH Gayle,1,0,1,NaN,False,NaN,NaN,NaN,Peshawar Zalmi,wickets 7,regular,EJG Morgan,Ahmed Shahab,Ahsan Raza
480,9,1075988,2017-02-10,2017,Dubai International Cricket Stadium,1,Karachi Kings,Peshawar Zalmi,2,1,Babar Azam,Hasan Ali,CH Gayle,0,0,0,NaN,False,NaN,NaN,NaN,Peshawar Zalmi,wickets 7,regular,EJG Morgan,Ahmed Shahab,Ahsan Raza
481,10,1075988,2017-02-10,2017,Dubai International Cricket Stadium,1,Karachi Kings,Peshawar Zalmi,2,2,Babar Azam,Hasan Ali,CH Gayle,0,0,0,NaN,False,NaN,NaN,NaN,Peshawar Zalmi,wickets 7,regular,EJG Morgan,Ahmed Shahab,Ahsan Raza
482,11,1075988,2017-02-10,2017,Dubai International Cricket Stadium,1,Karachi Kings,Peshawar Zalmi,2,3,Babar Azam,Hasan Ali,CH Gayle,0,0,0,NaN,True,Babar Azam,caught,DJG Sammy,Peshawar Zalmi,wickets 7,regular,EJG Morgan,Ahmed Shahab,Ahsan Raza
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68960,437,959179,2016-02-05,2016,Dubai International Cricket Stadium,2,Islamabad United,Peshawar Zalmi,3,5,Babar Azam,SW Tait,SR Watson,0,0,0,NaN,False,NaN,NaN,NaN,Peshawar Zalmi,runs 24,regular,Mohammad Asghar,Shozab Raza,Rashid Riaz
68961,438,959179,2016-02-05,2016,Dubai International Cricket Stadium,2,Islamabad United,Peshawar Zalmi,3,6,Babar Azam,SW Tait,SR Watson,0,0,0,NaN,False,NaN,NaN,NaN,Peshawar Zalmi,runs 24,regular,Mohammad Asghar,Shozab Raza,Rashid Riaz
68962,439,959179,2016-02-05,2016,Dubai International Cricket Stadium,2,Islamabad United,Peshawar Zalmi,3,7,Babar Azam,SW Tait,SR Watson,0,0,0,NaN,False,NaN,NaN,NaN,Peshawar Zalmi,runs 24,regular,Mohammad Asghar,Shozab Raza,Rashid Riaz
68966,443,959179,2016-02-05,2016,Dubai International Cricket Stadium,2,Islamabad United,Peshawar Zalmi,4,4,Babar Azam,Mohammad Asghar,SR Watson,0,1,1,wides,False,NaN,NaN,NaN,Peshawar Zalmi,runs 24,regular,Mohammad Asghar,Shozab Raza,Rashid Riaz
68967,444,959179,2016-02-05,2016,Dubai International Cricket Stadium,2,Islamabad United,Peshawar Zalmi,4,5,Babar Azam,Mohammad Asghar,SR Watson,0,0,0,NaN,True,Babar Azam,caught,Mohammad Hafeez,Peshawar Zalmi,runs 24,regular,Mohammad Asghar,Shozab Raza,Rashid Riaz