### Concatenation

In [1]:
import numpy as np
import pandas as pd

In [2]:
students=pd.read_csv("~/Machine Learning/Pandas/Datasets/students.csv")
courses=pd.read_csv("~/Machine Learning/Pandas/Datasets/courses.csv")
nov=pd.read_csv("~/Machine Learning/Pandas/Datasets/reg-month1.csv")
dec=pd.read_csv("~/Machine Learning/Pandas/Datasets/reg-month2.csv")
ipl=pd.read_csv("~/Machine Learning/Pandas/Datasets/ipl-matches.csv")
deliveries=pd.read_csv("~/Machine Learning/Pandas/Datasets/deliveries.csv")

##### concat() --> used for concatenating two tables

In [3]:
nov

    student_id  course_id
0           23          1
1           15          5
2           18          6
3           23          4
4           16          9
5           18          1
6            1          1
7            7          8
8           22          3
9           15          1
10          19          4
11           1          6
12           7         10
13          11          7
14          13          3
15          24          4
16          21          1
17          16          5
18          23          3
19          17          7
20          23          6
21          25          1
22          19          2
23          25         10
24           3          3

In [4]:
dec

    student_id  course_id
0            3          5
1           16          7
2           12         10
3           12          1
4           14          9
5            7          7
6            7          2
7           16          3
8           17         10
9           11          8
10          14          6
11          12          5
12          12          7
13          18          8
14           1         10
15           1          9
16           2          5
17           7          6
18          22          5
19          22          6
20          23          9
21          23          5
22          14          4
23          14          1
24          11         10
25          42          9
26          50          8
27          38          1

In [5]:
# ignore_index=True will make sure that your original indices are not repeated but rather new indices are made
pd.concat([nov,dec],ignore_index=True)

    student_id  course_id
0           23          1
1           15          5
2           18          6
3           23          4
4           16          9
5           18          1
6            1          1
7            7          8
8           22          3
9           15          1
10          19          4
11           1          6
12           7         10
13          11          7
14          13          3
15          24          4
16          21          1
17          16          5
18          23          3
19          17          7
20          23          6
21          25          1
22          19          2
23          25         10
24           3          3
25           3          5
26          16          7
27          12         10
28          12          1
29          14          9
30           7          7
31           7          2
32          16          3
33          17         10
34          11          8
35          14          6
36          12          5
37          12          7
38          18          8
39           1         10
40           1          9
41           2          5
42           7          6
43          22          5
44          22          6
45          23          9
46          23          5
47          14          4
48          14          1
49          11         10
50          42          9
51          50          8
52          38          1

In [6]:
# if we want to make multiple indices we can use keys parameter
pd.concat([nov,dec],keys=['Nov','Dec'])

        student_id  course_id
Nov 0           23          1
    1           15          5
    2           18          6
    3           23          4
    4           16          9
    5           18          1
    6            1          1
    7            7          8
    8           22          3
    9           15          1
    10          19          4
    11           1          6
    12           7         10
    13          11          7
    14          13          3
    15          24          4
    16          21          1
    17          16          5
    18          23          3
    19          17          7
    20          23          6
    21          25          1
    22          19          2
    23          25         10
    24           3          3
Dec 0            3          5
    1           16          7
    2           12         10
    3           12          1
    4           14          9
    5            7          7
    6            7          2
    7           16          3
    8           17         10
    9           11          8
    10          14          6
    11          12          5
    12          12          7
    13          18          8
    14           1         10
    15           1          9
    16           2          5
    17           7          6
    18          22          5
    19          22          6
    20          23          9
    21          23          5
    22          14          4
    23          14          1
    24          11         10
    25          42          9
    26          50          8
    27          38          1

In [7]:
#concatenating horizontally 
pd.concat([nov,dec],axis=1)

    student_id  course_id  student_id  course_id
0         23.0        1.0           3          5
1         15.0        5.0          16          7
2         18.0        6.0          12         10
3         23.0        4.0          12          1
4         16.0        9.0          14          9
5         18.0        1.0           7          7
6          1.0        1.0           7          2
7          7.0        8.0          16          3
8         22.0        3.0          17         10
9         15.0        1.0          11          8
10        19.0        4.0          14          6
11         1.0        6.0          12          5
12         7.0       10.0          12          7
13        11.0        7.0          18          8
14        13.0        3.0           1         10
15        24.0        4.0           1          9
16        21.0        1.0           2          5
17        16.0        5.0           7          6
18        23.0        3.0          22          5
19        17.0        7.0          22          6
20        23.0        6.0          23          9
21        25.0        1.0          23          5
22        19.0        2.0          14          4
23        25.0       10.0          14          1
24         3.0        3.0          11         10
25         NaN        NaN          42          9
26         NaN        NaN          50          8
27         NaN        NaN          38          1

### Merge using Joins

In [9]:
regs=pd.concat([nov,dec],ignore_index=True)
regs

    student_id  course_id
0           23          1
1           15          5
2           18          6
3           23          4
4           16          9
5           18          1
6            1          1
7            7          8
8           22          3
9           15          1
10          19          4
11           1          6
12           7         10
13          11          7
14          13          3
15          24          4
16          21          1
17          16          5
18          23          3
19          17          7
20          23          6
21          25          1
22          19          2
23          25         10
24           3          3
25           3          5
26          16          7
27          12         10
28          12          1
29          14          9
30           7          7
31           7          2
32          16          3
33          17         10
34          11          8
35          14          6
36          12          5
37          12          7
38          18          8
39           1         10
40           1          9
41           2          5
42           7          6
43          22          5
44          22          6
45          23          9
46          23          5
47          14          4
48          14          1
49          11         10
50          42          9
51          50          8
52          38          1

In [12]:
#joins (inner,outer,left,right,self) --> same like SQL
students.merge(regs,how='inner',on='student_id')

    student_id                name  partner  course_id
0            1       Kailash Harjo       23          1
1            1       Kailash Harjo       23          6
2            1       Kailash Harjo       23         10
3            1       Kailash Harjo       23          9
4            2         Esha Butala        1          5
5            3      Parveen Bhalla        3          3
6            3      Parveen Bhalla        3          5
7            7        Tarun Thaker        9          8
8            7        Tarun Thaker        9         10
9            7        Tarun Thaker        9          7
10           7        Tarun Thaker        9          2
11           7        Tarun Thaker        9          6
12          11  David Mukhopadhyay       20          7
13          11  David Mukhopadhyay       20          8
14          11  David Mukhopadhyay       20         10
15          12          Radha Dutt       19         10
16          12          Radha Dutt       19          1
17          12          Radha Dutt       19          5
18          12          Radha Dutt       19          7
19          13      Munni Varghese       24          3
20          14    Pranab Natarajan       22          9
21          14    Pranab Natarajan       22          6
22          14    Pranab Natarajan       22          4
23          14    Pranab Natarajan       22          1
24          15           Preet Sha       16          5
25          15           Preet Sha       16          1
26          16        Elias Dodiya       25          9
27          16        Elias Dodiya       25          5
28          16        Elias Dodiya       25          7
29          16        Elias Dodiya       25          3
30          17        Yasmin Palan        7          7
31          17        Yasmin Palan        7         10
32          18     Fardeen Mahabir       13          6
33          18     Fardeen Mahabir       13          1
34          18     Fardeen Mahabir       13          8
35          19        Qabeel Raman       12          4
36          19        Qabeel Raman       12          2
37          21          Seema Kota       15          1
38          22          Yash Sethi       21          3
39          22          Yash Sethi       21          5
40          22          Yash Sethi       21          6
41          23      Chhavi Lachman       18          1
42          23      Chhavi Lachman       18          4
43          23      Chhavi Lachman       18          3
44          23      Chhavi Lachman       18          6
45          23      Chhavi Lachman       18          9
46          23      Chhavi Lachman       18          5
47          24        Radhika Suri       17          4
48          25     Shashank D’Alia        2          1
49          25     Shashank D’Alia        2         10

##### 1. find total revenue generated

In [23]:
courses.merge(regs,on='course_id')['price'].sum()

np.int64(154247)

##### 2. find month by month revenue

In [33]:
both_months=pd.concat([nov,dec],keys=['Nov','Dec']).reset_index()
both_months.merge(regs,on='student_id')

    level_0  level_1  student_id  course_id_x  course_id_y
0       Nov        0          23            1            1
1       Nov        0          23            1            4
2       Nov        0          23            1            3
3       Nov        0          23            1            6
4       Nov        0          23            1            9
..      ...      ...         ...          ...          ...
174     Dec       24          11           10            8
175     Dec       24          11           10           10
176     Dec       25          42            9            9
177     Dec       26          50            8            8
178     Dec       27          38            1            1

[179 rows x 5 columns]

In [30]:
both_months

   level_0  level_1  student_id  course_id
0      Nov        0          23          1
1      Nov        1          15          5
2      Nov        2          18          6
3      Nov        3          23          4
4      Nov        4          16          9
5      Nov        5          18          1
6      Nov        6           1          1
7      Nov        7           7          8
8      Nov        8          22          3
9      Nov        9          15          1
10     Nov       10          19          4
11     Nov       11           1          6
12     Nov       12           7         10
13     Nov       13          11          7
14     Nov       14          13          3
15     Nov       15          24          4
16     Nov       16          21          1
17     Nov       17          16          5
18     Nov       18          23          3
19     Nov       19          17          7
20     Nov       20          23          6
21     Nov       21          25          1
22     Nov       22          19          2
23     Nov       23          25         10
24     Nov       24           3          3
25     Dec        0           3          5
26     Dec        1          16          7
27     Dec        2          12         10
28     Dec        3          12          1
29     Dec        4          14          9
30     Dec        5           7          7
31     Dec        6           7          2
32     Dec        7          16          3
33     Dec        8          17         10
34     Dec        9          11          8
35     Dec       10          14          6
36     Dec       11          12          5
37     Dec       12          12          7
38     Dec       13          18          8
39     Dec       14           1         10
40     Dec       15           1          9
41     Dec       16           2          5
42     Dec       17           7          6
43     Dec       18          22          5
44     Dec       19          22          6
45     Dec       20          23          9
46     Dec       21          23          5
47     Dec       22          14          4
48     Dec       23          14          1
49     Dec       24          11         10
50     Dec       25          42          9
51     Dec       26          50          8
52     Dec       27          38          1